[package]
name = "ion-macros"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Macro System - Compile-time code generation"
license = "MIT"

[dependencies]
ion-ast = { path = "../ast" }
ion-parser = { path = "../parser" }

[scripts]
test = "zig test src/macro_system.zig"
