[package]
name = "home-generics"
version = "0.1.0"
authors = ["Home Contributors"]
description = "Home Generics System - Generic types and functions"
license = "MIT"

[dependencies]
home-ast = { path = "../ast" }
home-types = { path = "../types" }

[scripts]
test = "zig test src/generic_system.zig"
