[package]
name = "ion-generics"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Generics System - Generic types and functions"
license = "MIT"

[dependencies]
ion-ast = { path = "../ast" }
ion-types = { path = "../types" }

[scripts]
test = "zig test src/generic_system.zig"
