// Home Runtime — ported from Bun.
// Upstream:  packages/runtime/upstream/src/ast/server_component_boundary.zig
// Pinned SHA: fd0b6f1a271fca0b8124b69f230b100f4d636af6
//
// Renames applied (per packages/runtime/README.md naming convention):
//   - `@import("bun")` -> `@import("home")`
//   - `bun.assert` -> `home_rt.assert`
//   - `bun.unsafeAssert` -> `home_rt.assert` (no separate "unsafe" variant
//     exists on Home yet; the upstream's `unsafeAssert` is identical in
//     release builds, where it's a no-op).
//   - `bun.bit_set.DynamicBitSetUnmanaged` -> `std.bit_set.DynamicBitSetUnmanaged`.
//     Upstream wraps the std type one-to-one; we just elide the wrapper.
//   - `js_ast.Index` / `js_ast.ServerComponentBoundary` / `js_ast.UseDirective`
//     -> direct imports of the sibling Home modules.

//! Represents a boundary between client and server code. Every boundary
//! gets bundled twice, once for the desired target, and once to generate
//! a module of "references". Specifically, the generated file takes the
//! canonical Ast as input to derive a wrapper. See `Framework.ServerComponents`
//! for more details about this generated file.
//!
//! This is sometimes abbreviated as SCB
use_directive: UseDirective,

/// The index of the original file.
source_index: Index.Int,

/// Index to the file imported on the opposite platform, which is
/// generated by the bundler. For client components, this is the
/// server's code. For server actions, this is the client's code.
reference_source_index: Index.Int,

/// When `bake.Framework.ServerComponents.separate_ssr_graph` is enabled this
/// points to the separated module. When the SSR graph is not separate, this is
/// equal to `reference_source_index`
//
// TODO: Is this used for server actions.
ssr_source_index: Index.Int,

/// The requirements for this data structure is to have reasonable lookup
/// speed, but also being able to pull a `[]const Index.Int` of all
/// boundaries for iteration.
pub const List = struct {
    list: std.MultiArrayList(ServerComponentBoundary) = .{},
    /// Used to facilitate fast lookups into `items` by `.source_index`
    map: Map = .{},

    const Map = std.ArrayHashMapUnmanaged(void, void, struct {}, true);

    /// Can only be called on the bundler thread.
    pub fn put(
        m: *List,
        allocator: std.mem.Allocator,
        source_index: Index.Int,
        use_directive: UseDirective,
        reference_source_index: Index.Int,
        ssr_source_index: Index.Int,
    ) !void {
        try m.list.append(allocator, .{
            .source_index = source_index,
            .use_directive = use_directive,
            .reference_source_index = reference_source_index,
            .ssr_source_index = ssr_source_index,
        });
        const gop = try m.map.getOrPutAdapted(
            allocator,
            source_index,
            Adapter{ .list = m.list.slice() },
        );
        home_rt.assert(!gop.found_existing);
    }

    /// Can only be called on the bundler thread.
    pub fn getIndex(l: *const List, real_source_index: Index.Int) ?usize {
        return l.map.getIndexAdapted(
            real_source_index,
            Adapter{ .list = l.list.slice() },
        );
    }

    /// Use this to improve speed of accessing fields at the cost of
    /// storing more pointers. Invalidated when input is mutated.
    pub fn slice(l: List) Slice {
        return .{ .list = l.list.slice(), .map = l.map };
    }

    pub const Slice = struct {
        list: std.MultiArrayList(ServerComponentBoundary).Slice,
        map: Map,

        pub fn getIndex(l: *const Slice, real_source_index: Index.Int) ?usize {
            return l.map.getIndexAdapted(
                real_source_index,
                Adapter{ .list = l.list },
            ) orelse return null;
        }

        pub fn getReferenceSourceIndex(l: *const Slice, real_source_index: Index.Int) ?u32 {
            const i = l.map.getIndexAdapted(
                real_source_index,
                Adapter{ .list = l.list },
            ) orelse return null;
            home_rt.assert(l.list.capacity > 0); // optimize MultiArrayList.Slice.items
            return l.list.items(.reference_source_index)[i];
        }

        pub fn bitSet(scbs: Slice, alloc: std.mem.Allocator, input_file_count: usize) !home_rt.bit_set.DynamicBitSetUnmanaged {
            var scb_bitset = try home_rt.bit_set.DynamicBitSetUnmanaged.initEmpty(alloc, input_file_count);
            for (scbs.list.items(.source_index)) |source_index| {
                scb_bitset.set(source_index);
            }
            return scb_bitset;
        }
    };

    pub const Adapter = struct {
        list: std.MultiArrayList(ServerComponentBoundary).Slice,

        pub fn hash(_: Adapter, key: Index.Int) u32 {
            return std.hash.int(@as(u32, key));
        }

        pub fn eql(adapt: Adapter, a: Index.Int, _: void, b_index: usize) bool {
            home_rt.assert(adapt.list.capacity > 0); // optimize MultiArrayList.Slice.items
            return a == adapt.list.items(.source_index)[b_index];
        }
    };
};

const std = @import("std");

const home_rt = @import("home");

const base = @import("base.zig");
const Index = base.Index;
const use_directive_mod = @import("use_directive.zig");
const UseDirective = use_directive_mod.UseDirective;

const ServerComponentBoundary = @This();

test "List.put inserts + getIndex finds entries" {
    const allocator = std.testing.allocator;
    var list: List = .{};
    defer {
        list.list.deinit(allocator);
        list.map.deinit(allocator);
    }

    try list.put(allocator, 7, .client, 100, 200);
    try list.put(allocator, 9, .server, 101, 201);

    try std.testing.expectEqual(@as(usize, 0), list.getIndex(7).?);
    try std.testing.expectEqual(@as(usize, 1), list.getIndex(9).?);
    try std.testing.expect(list.getIndex(123) == null);
}

test "Slice.getReferenceSourceIndex / bitSet" {
    const allocator = std.testing.allocator;
    var list: List = .{};
    defer {
        list.list.deinit(allocator);
        list.map.deinit(allocator);
    }

    try list.put(allocator, 3, .client, 30, 31);
    try list.put(allocator, 5, .server, 50, 51);

    const view = list.slice();
    try std.testing.expectEqual(@as(u32, 30), view.getReferenceSourceIndex(3).?);
    try std.testing.expectEqual(@as(u32, 50), view.getReferenceSourceIndex(5).?);
    try std.testing.expect(view.getReferenceSourceIndex(404) == null);

    var bits = try view.bitSet(allocator, 16);
    defer bits.deinit(allocator);
    try std.testing.expect(bits.isSet(3));
    try std.testing.expect(bits.isSet(5));
    try std.testing.expect(!bits.isSet(4));
}
