[package]
name = "ion-types"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Type System - Type checking, ownership, and safety"
license = "MIT"

[dependencies]
ion-ast = { path = "../ast" }

[scripts]
test = "zig test src/type_system.zig"
