// Copied from bun/src/jsc/ResolvedSource.zig at upstream SHA
// fd0b6f1a271fca0b8124b69f230b100f4d636af6. MIT — see ../cli/LICENSE.bun.md.
//
// Upstream `pub const Tag = @import("ResolvedSourceTag").ResolvedSourceTag` is a
// build-system module (codegen → `build/*/codegen/ResolvedSourceTag.zig`). The
// codegen output contains both structural variants (`Javascript`,
// `PackageJsonTypeModule`, …) and an open-ended `(1 << 9) | id` half generated
// from the `HardcodedModule` enum.
//
// Home's port keeps the same `extern struct` shape so the C ABI matches the
// upstream `ResolvedSource` and reuses `Tag` as a `u32` newtype with the
// structural variants enumerated as constants. The hardcoded-module table
// re-attaches alongside `ModuleLoader` in Phase 12.2.
//
// `bun.String` now points at the real tagged string shape used across the
// runtime while the rest of the JSC bridge re-attaches in Phase 12.2.

const std = @import("std");

const String = @import("home").String;

pub const JSValue = @import("home").jsc.JSValue;

/// Mirrors `build/*/codegen/ResolvedSourceTag.zig`. The full `(1 << 9) | id`
/// hardcoded-module half is generated at build time from `HardcodedModule`
/// and is omitted here — `Tag` round-trips as a plain `u32` so unknown
/// generator-supplied ids stay representable. Structural variants are kept
/// in lock-step with `src/jsc/bindings/headers-handwritten.h` and the Rust
/// mirror in `crate::resolved_source_tag`.
pub const Tag = enum(u32) {
    javascript = 0,
    package_json_type_module = 1,
    package_json_type_commonjs = 2,
    wasm = 3,
    object = 4,
    file = 5,
    esm = 6,
    json_for_object_loader = 7,
    /// Generate an object with `default` set to all the exports, including a
    /// `default` property.
    exports_object = 8,
    /// Generate a module that only exports `default` = the input JSValue.
    export_default_object = 9,
    /// Signal upwards that the matching value in `require.extensions`
    /// should be used.
    common_js_custom_extension = 10,

    // Built-in modules are loaded through `InternalModuleRegistry` by numerical
    // ID; here they are represented as `(1 << 9) | id`. These values are
    // generated by Bun's codegen (`build/*/codegen/ResolvedSourceTag.zig`) and
    // MUST match the linked C++ objects' `InternalModuleRegistryConstants` —
    // the C++ module loader (ModuleLoader.cpp) masks off `InternalModuleRegistryFlag`
    // (512) and calls `internalModuleRegistry()->requireId(... tag & 511)`.
    // Copied verbatim from `~/Code/bun/build/release/codegen/ResolvedSourceTag.zig`.
    @"bun:ffi" = 512,
    @"bun:sql" = 513,
    @"bun:sqlite" = 514,
    @"internal:abort_listener" = 515,
    @"internal:assert/assertion_error" = 516,
    @"internal:assert/calltracker" = 517,
    @"internal:assert/myers_diff" = 518,
    @"internal:assert/utils" = 519,
    @"internal:buffer" = 520,
    @"internal:cluster/RoundRobinHandle" = 521,
    @"internal:cluster/Worker" = 522,
    @"internal:cluster/child" = 523,
    @"internal:cluster/isPrimary" = 524,
    @"internal:cluster/primary" = 525,
    @"internal:crypto/x509" = 526,
    @"internal:debugger" = 527,
    @"internal:errors" = 528,
    @"internal:fifo" = 529,
    @"internal:fixed_queue" = 530,
    @"internal:freelist" = 531,
    @"internal:fs/cp-sync" = 532,
    @"internal:fs/cp" = 533,
    @"internal:fs/glob" = 534,
    @"internal:fs/streams" = 535,
    @"internal:html" = 536,
    @"internal:http" = 537,
    @"internal:http/FakeSocket" = 538,
    @"internal:linkedlist" = 539,
    @"internal:net/isIP" = 540,
    @"internal:perf_hooks/monitorEventLoopDelay" = 541,
    @"internal:primordials" = 542,
    @"internal:promisify" = 543,
    @"internal:shared" = 544,
    @"internal:sql/errors" = 545,
    @"internal:sql/mysql" = 546,
    @"internal:sql/postgres" = 547,
    @"internal:sql/query" = 548,
    @"internal:sql/shared" = 549,
    @"internal:sql/sqlite" = 550,
    @"internal:stream/promises" = 551,
    @"internal:stream" = 552,
    @"internal:streams/add-abort-signal" = 553,
    @"internal:streams/compose" = 554,
    @"internal:streams/destroy" = 555,
    @"internal:streams/duplex" = 556,
    @"internal:streams/duplexify" = 557,
    @"internal:streams/duplexpair" = 558,
    @"internal:streams/end-of-stream" = 559,
    @"internal:streams/from" = 560,
    @"internal:streams/lazy_transform" = 561,
    @"internal:streams/legacy" = 562,
    @"internal:streams/native-readable" = 563,
    @"internal:streams/operators" = 564,
    @"internal:streams/passthrough" = 565,
    @"internal:streams/pipeline" = 566,
    @"internal:streams/readable" = 567,
    @"internal:streams/state" = 568,
    @"internal:streams/transform" = 569,
    @"internal:streams/utils" = 570,
    @"internal:streams/writable" = 571,
    @"internal:timers" = 572,
    @"internal:tls" = 573,
    @"internal:tty" = 574,
    @"internal:url" = 575,
    @"internal:util/colors" = 576,
    @"internal:util/deprecate" = 577,
    @"internal:util/inspect" = 578,
    @"internal:util/mime" = 579,
    @"internal:validators" = 580,
    @"internal:webstreams_adapters" = 581,
    @"node:_http2_upgrade" = 582,
    @"node:_http_agent" = 583,
    @"node:_http_client" = 584,
    @"node:_http_common" = 585,
    @"node:_http_incoming" = 586,
    @"node:_http_outgoing" = 587,
    @"node:_http_server" = 588,
    @"node:_stream_duplex" = 589,
    @"node:_stream_passthrough" = 590,
    @"node:_stream_readable" = 591,
    @"node:_stream_transform" = 592,
    @"node:_stream_wrap" = 593,
    @"node:_stream_writable" = 594,
    @"node:_tls_common" = 595,
    @"node:assert/strict" = 596,
    @"node:assert" = 597,
    @"node:async_hooks" = 598,
    @"node:child_process" = 599,
    @"node:cluster" = 600,
    @"node:console" = 601,
    @"node:crypto" = 602,
    @"node:dgram" = 603,
    @"node:diagnostics_channel" = 604,
    @"node:dns/promises" = 605,
    @"node:dns" = 606,
    @"node:domain" = 607,
    @"node:events" = 608,
    @"node:fs/promises" = 609,
    @"node:fs" = 610,
    @"node:http" = 611,
    @"node:http2" = 612,
    @"node:https" = 613,
    @"node:inspector/promises" = 614,
    @"node:inspector" = 615,
    @"node:net" = 616,
    @"node:os" = 617,
    @"node:path/posix" = 618,
    @"node:path" = 619,
    @"node:path/win32" = 620,
    @"node:perf_hooks" = 621,
    @"node:punycode" = 622,
    @"node:querystring" = 623,
    @"node:readline/promises" = 624,
    @"node:readline" = 625,
    @"node:repl" = 626,
    @"node:stream/consumers" = 627,
    @"node:stream/promises" = 628,
    @"node:stream" = 629,
    @"node:stream/web" = 630,
    @"node:test" = 631,
    @"node:timers/promises" = 632,
    @"node:timers" = 633,
    @"node:tls" = 634,
    @"node:trace_events" = 635,
    @"node:tty" = 636,
    @"node:url" = 637,
    @"node:util" = 638,
    @"node:v8" = 639,
    @"node:vm" = 640,
    @"node:wasi" = 641,
    @"node:worker_threads" = 642,
    @"node:zlib" = 643,
    @"isomorphic-fetch" = 644,
    @"node-fetch" = 645,
    @"undici" = 646,
    @"vercel_fetch" = 647,
    @"ws" = 648,
    @"bun:internal-for-testing" = 649,
    // Native modules come after the JS modules
    @"bun:test" = 650,
    @"bun:jsc" = 651,
    @"bun:app" = 652,
    @"node:buffer" = 653,
    @"node:constants" = 654,
    @"node:string_decoder" = 655,
    @"node:util/types" = 656,
    @"utf-8-validate" = 657,
    @"abort-controller" = 658,
    @"node:module" = 659,
    @"node:process" = 660,
    @"bun" = 661,
    _,
};

pub const ResolvedSource = extern struct {
    /// Specifier's lifetime is the caller from C++
    /// https://github.com/oven-sh/bun/issues/9521
    specifier: String = String.empty,
    source_code: String = String.empty,

    /// source_url is eventually deref'd on success
    source_url: String = String.empty,

    is_commonjs_module: bool = false,

    /// When .tag is .common_js_custom_extension, this is special-cased to hold
    /// the JSFunction extension. It is kept alive by
    /// - This structure is stored on the stack
    /// - There is a JSC::Strong reference to it
    cjs_custom_extension_index: JSValue = .zero,

    allocator: ?*anyopaque = null,

    jsvalue_for_export: JSValue = .zero,

    tag: Tag = .javascript,

    /// This is for source_code
    source_code_needs_deref: bool = true,
    already_bundled: bool = false,

    // -- Bytecode cache fields --
    bytecode_cache: ?[*]u8 = null,
    bytecode_cache_size: usize = 0,
    module_info: ?*anyopaque = null,
    /// The file path used as the source origin for bytecode cache validation.
    /// JSC validates bytecode by checking if the origin URL matches exactly what
    /// was used at build time. If empty, the origin is derived from source_url.
    /// This is converted to a file:// URL on the C++ side.
    bytecode_origin_path: String = String.empty,
};

test "ResolvedSource is an extern struct with default Javascript tag" {
    const rs: ResolvedSource = .{};
    try std.testing.expectEqual(Tag.javascript, rs.tag);
    try std.testing.expectEqual(JSValue.zero, rs.cjs_custom_extension_index);
    try std.testing.expectEqual(JSValue.zero, rs.jsvalue_for_export);
    try std.testing.expect(rs.source_code_needs_deref);
    try std.testing.expect(!rs.already_bundled);
    try std.testing.expect(rs.allocator == null);
    try std.testing.expect(rs.bytecode_cache == null);
    try std.testing.expect(rs.module_info == null);
}

test "Tag structural variants stay in lock-step with headers-handwritten.h" {
    try std.testing.expectEqual(@as(u32, 0), @intFromEnum(Tag.javascript));
    try std.testing.expectEqual(@as(u32, 1), @intFromEnum(Tag.package_json_type_module));
    try std.testing.expectEqual(@as(u32, 2), @intFromEnum(Tag.package_json_type_commonjs));
    try std.testing.expectEqual(@as(u32, 3), @intFromEnum(Tag.wasm));
    try std.testing.expectEqual(@as(u32, 4), @intFromEnum(Tag.object));
    try std.testing.expectEqual(@as(u32, 5), @intFromEnum(Tag.file));
    try std.testing.expectEqual(@as(u32, 6), @intFromEnum(Tag.esm));
    try std.testing.expectEqual(@as(u32, 7), @intFromEnum(Tag.json_for_object_loader));
    try std.testing.expectEqual(@as(u32, 8), @intFromEnum(Tag.exports_object));
    try std.testing.expectEqual(@as(u32, 9), @intFromEnum(Tag.export_default_object));
    try std.testing.expectEqual(@as(u32, 10), @intFromEnum(Tag.common_js_custom_extension));
}

test "String stub size matches the upstream BunString" {
    try std.testing.expectEqual(@as(usize, 24), @sizeOf(String));
}
