// Generated by scripts/gen-jstype-abi.mjs — do not edit by hand.
//
// Zig reads JSC::JSCell::type() as an enum byte, so a table that disagrees
// with the linked WebKit does not fail to link: it silently reclassifies
// values (a Promise read as a Map). Every member of Home's JSType.zig is
// asserted here, because a member that is merely unasserted is a member that
// can drift undetected when the WebKit pin moves.
//
// WebKit cd821fecca0d39c8 (Bun's pinned WEBKIT_VERSION; see build.zig).
// Regenerate after moving that pin:  node scripts/gen-jstype-abi.mjs
#include <JavaScriptCore/JSType.h>

static_assert(JSC::CellType == 0);                                // JSType.Cell
static_assert(JSC::StructureType == 1);                           // JSType.Structure
static_assert(JSC::StringType == 2);                              // JSType.String
static_assert(JSC::HeapBigIntType == 3);                          // JSType.HeapBigInt
static_assert(JSC::SymbolType == 4);                              // JSType.Symbol
static_assert(JSC::GetterSetterType == 5);                        // JSType.GetterSetter
static_assert(JSC::CustomGetterSetterType == 6);                  // JSType.CustomGetterSetter
static_assert(JSC::APIValueWrapperType == 7);                     // JSType.APIValueWrapper
static_assert(JSC::NativeExecutableType == 8);                    // JSType.NativeExecutable
static_assert(JSC::ProgramExecutableType == 9);                   // JSType.ProgramExecutable
static_assert(JSC::ModuleProgramExecutableType == 10);            // JSType.ModuleProgramExecutable
static_assert(JSC::EvalExecutableType == 11);                     // JSType.EvalExecutable
static_assert(JSC::FunctionExecutableType == 12);                 // JSType.FunctionExecutable
static_assert(JSC::UnlinkedFunctionExecutableType == 13);         // JSType.UnlinkedFunctionExecutable
static_assert(JSC::UnlinkedProgramCodeBlockType == 14);           // JSType.UnlinkedProgramCodeBlock
static_assert(JSC::UnlinkedModuleProgramCodeBlockType == 15);     // JSType.UnlinkedModuleProgramCodeBlock
static_assert(JSC::UnlinkedEvalCodeBlockType == 16);              // JSType.UnlinkedEvalCodeBlock
static_assert(JSC::UnlinkedFunctionCodeBlockType == 17);          // JSType.UnlinkedFunctionCodeBlock
static_assert(JSC::CodeBlockType == 18);                          // JSType.CodeBlock
static_assert(JSC::JSCellButterflyType == 19);                    // JSType.JSCellButterfly
static_assert(JSC::JSSourceCodeType == 20);                       // JSType.JSSourceCode
static_assert(JSC::JSSlimPromiseReactionType == 21);              // JSType.SlimPromiseReaction
static_assert(JSC::JSFullPromiseReactionType == 22);              // JSType.FullPromiseReaction
static_assert(JSC::JSPromiseCombinatorsContextType == 23);        // JSType.PromiseAllContext
static_assert(JSC::JSPromiseCombinatorsGlobalContextType == 24);  // JSType.PromiseAllGlobalContext
static_assert(JSC::JSWebAssemblyStreamingContextType == 25);      // JSType.WebAssemblyStreamingContext
static_assert(JSC::JSMicrotaskDispatcherType == 26);              // JSType.JSMicrotaskDispatcher
static_assert(JSC::ModuleRegistryEntryType == 27);                // JSType.ModuleRegistryEntry
static_assert(JSC::ModuleLoadingContextType == 28);               // JSType.ModuleLoadingContext
static_assert(JSC::ModuleLoaderPayloadType == 29);                // JSType.ModuleLoaderPayload
static_assert(JSC::ModuleGraphLoadingStateType == 30);            // JSType.ModuleGraphLoadingState
static_assert(JSC::JSModuleLoaderType == 31);                     // JSType.JSModuleLoader
static_assert(JSC::SentinelType == 32);                           // JSType.Sentinel
static_assert(JSC::ObjectType == 33);                             // JSType.Object
static_assert(JSC::FinalObjectType == 34);                        // JSType.FinalObject
static_assert(JSC::JSCalleeType == 35);                           // JSType.JSCallee
static_assert(JSC::JSFunctionType == 36);                         // JSType.JSFunction
static_assert(JSC::InternalFunctionType == 37);                   // JSType.InternalFunction
static_assert(JSC::NullSetterFunctionType == 38);                 // JSType.NullSetterFunction
static_assert(JSC::BooleanObjectType == 39);                      // JSType.BooleanObject
static_assert(JSC::NumberObjectType == 40);                       // JSType.NumberObject
static_assert(JSC::ErrorInstanceType == 41);                      // JSType.ErrorInstance
static_assert(JSC::GlobalProxyType == 42);                        // JSType.GlobalProxy
static_assert(JSC::DirectArgumentsType == 43);                    // JSType.DirectArguments
static_assert(JSC::ScopedArgumentsType == 44);                    // JSType.ScopedArguments
static_assert(JSC::ClonedArgumentsType == 45);                    // JSType.ClonedArguments
static_assert(JSC::ArrayType == 46);                              // JSType.Array
static_assert(JSC::DerivedArrayType == 47);                       // JSType.DerivedArray
static_assert(JSC::ArrayBufferType == 48);                        // JSType.ArrayBuffer
static_assert(JSC::Int8ArrayType == 49);                          // JSType.Int8Array
static_assert(JSC::Uint8ArrayType == 50);                         // JSType.Uint8Array
static_assert(JSC::Uint8ClampedArrayType == 51);                  // JSType.Uint8ClampedArray
static_assert(JSC::Int16ArrayType == 52);                         // JSType.Int16Array
static_assert(JSC::Uint16ArrayType == 53);                        // JSType.Uint16Array
static_assert(JSC::Int32ArrayType == 54);                         // JSType.Int32Array
static_assert(JSC::Uint32ArrayType == 55);                        // JSType.Uint32Array
static_assert(JSC::Float16ArrayType == 56);                       // JSType.Float16Array
static_assert(JSC::Float32ArrayType == 57);                       // JSType.Float32Array
static_assert(JSC::Float64ArrayType == 58);                       // JSType.Float64Array
static_assert(JSC::BigInt64ArrayType == 59);                      // JSType.BigInt64Array
static_assert(JSC::BigUint64ArrayType == 60);                     // JSType.BigUint64Array
static_assert(JSC::DataViewType == 61);                           // JSType.DataView
static_assert(JSC::GlobalObjectType == 62);                       // JSType.GlobalObject
static_assert(JSC::GlobalLexicalEnvironmentType == 63);           // JSType.GlobalLexicalEnvironment
static_assert(JSC::LexicalEnvironmentType == 64);                 // JSType.LexicalEnvironment
static_assert(JSC::ModuleEnvironmentType == 65);                  // JSType.ModuleEnvironment
static_assert(JSC::StrictEvalActivationType == 66);               // JSType.StrictEvalActivation
static_assert(JSC::WithScopeType == 67);                          // JSType.WithScope
static_assert(JSC::AsyncDisposableStackType == 68);               // JSType.AsyncDisposableStack
static_assert(JSC::DisposableStackType == 69);                    // JSType.DisposableStack
static_assert(JSC::ModuleNamespaceObjectType == 70);              // JSType.ModuleNamespaceObject
static_assert(JSC::ShadowRealmType == 71);                        // JSType.ShadowRealm
static_assert(JSC::RegExpObjectType == 72);                       // JSType.RegExpObject
static_assert(JSC::JSDateType == 73);                             // JSType.JSDate
static_assert(JSC::ProxyObjectType == 74);                        // JSType.ProxyObject
static_assert(JSC::JSGeneratorType == 75);                        // JSType.Generator
static_assert(JSC::JSAsyncFunctionGeneratorType == 76);           // JSType.AsyncFunctionGenerator
static_assert(JSC::JSAsyncGeneratorType == 77);                   // JSType.AsyncGenerator
static_assert(JSC::JSArrayIteratorType == 78);                    // JSType.JSArrayIterator
static_assert(JSC::JSIteratorType == 79);                         // JSType.Iterator
static_assert(JSC::JSIteratorHelperType == 80);                   // JSType.IteratorHelper
static_assert(JSC::JSMapIteratorType == 81);                      // JSType.MapIterator
static_assert(JSC::JSSetIteratorType == 82);                      // JSType.SetIterator
static_assert(JSC::JSStringIteratorType == 83);                   // JSType.StringIterator
static_assert(JSC::JSWrapForValidIteratorType == 84);             // JSType.WrapForValidIterator
static_assert(JSC::JSRegExpStringIteratorType == 85);             // JSType.RegExpStringIterator
static_assert(JSC::JSAsyncFromSyncIteratorType == 86);            // JSType.AsyncFromSyncIterator
static_assert(JSC::JSPromiseType == 87);                          // JSType.JSPromise
static_assert(JSC::JSMapType == 88);                              // JSType.Map
static_assert(JSC::JSSetType == 89);                              // JSType.Set
static_assert(JSC::JSWeakMapType == 90);                          // JSType.WeakMap
static_assert(JSC::JSWeakSetType == 91);                          // JSType.WeakSet
static_assert(JSC::WebAssemblyModuleType == 92);                  // JSType.WebAssemblyModule
static_assert(JSC::WebAssemblyInstanceType == 93);                // JSType.WebAssemblyInstance
static_assert(JSC::WebAssemblyGCObjectType == 94);                // JSType.WebAssemblyGCObject
static_assert(JSC::StringObjectType == 95);                       // JSType.StringObject
static_assert(JSC::DerivedStringObjectType == 96);                // JSType.DerivedStringObject
static_assert(JSC::InternalFieldTupleType == 97);                 // JSType.InternalFieldTuple
