[package]
name = "home-patterns"
version = "0.1.0"
authors = ["Home Contributors"]
description = "Home Pattern Matching - Advanced pattern matching support"
license = "MIT"

[dependencies]
home-ast = { path = "../ast" }
home-types = { path = "../types" }

[scripts]
test = "zig test src/pattern_matching.zig"
