[package]
name = "ion-patterns"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Pattern Matching - Advanced pattern matching support"
license = "MIT"

[dependencies]
ion-ast = { path = "../ast" }
ion-types = { path = "../types" }

[scripts]
test = "zig test src/pattern_matching.zig"
