[package]
name = "basics"
version = "0.1.0"
authors = ["Home Contributors"]
description = "Home Basics - Core functionality and web framework utilities"
license = "MIT"

[dependencies]
home-ast = { path = "../ast" }
home-types = { path = "../types" }

[scripts]
test = "zig test src/basics.zig"
