[package]
name = "ion-database"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Database - SQL database access with SQLite driver"
license = "MIT"

[dependencies]
# No external dependencies - uses native SQLite

[scripts]
test = "zig test src/database.zig"
