// generated by cppbind.ts from functions marked with [[ZIG_EXPORT(mode)]]

const bun = @import("bun");
const jsc = bun.jsc;
const HTTPServerAgent = bun.jsc.Debugger.HTTPServerAgent;
const Environment = bun.Environment;

/// Source: Bun__WTFStringImpl__hasPrefix
pub extern fn Bun__WTFStringImpl__hasPrefix(impl: ?*const bun.WTF._StringImplStruct, bytes: ?[*]const u8, length: usize) bool;

/// Source: Bun__WTFStringImpl__deref
pub extern fn Bun__WTFStringImpl__deref(impl: ?*bun.WTF._StringImplStruct) void;

/// Source: Bun__WTFStringImpl__ref
pub extern fn Bun__WTFStringImpl__ref(impl: ?*bun.WTF._StringImplStruct) void;

/// Source: Bun__WTFStringImpl__destroy
pub extern fn Bun__WTFStringImpl__destroy(impl: ?*bun.WTF._StringImplStruct) void;

/// Source: BunString__fromJS
pub extern fn BunString__fromJS(globalObject: ?*jsc.JSGlobalObject, encodedValue: jsc.JSValue, bunString: ?*bun.String) bool;

/// Source: BunString__createAtom
pub extern fn BunString__createAtom(bytes: ?[*]const u8, length: usize) bun.String;

/// Source: BunString__tryCreateAtom
pub extern fn BunString__tryCreateAtom(bytes: ?[*]const u8, length: usize) bun.String;

/// Source: BunString__createUTF8ForJS
pub fn BunString__createUTF8ForJS(globalObject: *jsc.JSGlobalObject, ptr: ?[*]const u8, length: usize) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const value = raw.BunString__createUTF8ForJS(globalObject, ptr, length);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.BunString__createUTF8ForJS(globalObject, ptr, length);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: BunString__transferToJS
pub fn BunString__transferToJS(bunString: ?*bun.String, globalObject: *jsc.JSGlobalObject) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const value = raw.BunString__transferToJS(bunString, globalObject);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.BunString__transferToJS(bunString, globalObject);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: BunString__toInt32
pub extern fn BunString__toInt32(bunString: ?*const bun.String) i64;

/// Source: BunString__toThreadSafe
pub extern fn BunString__toThreadSafe(str: ?*bun.String) void;

/// Source: BunString__toJS
pub fn BunString__toJS(globalObject: *jsc.JSGlobalObject, bunString: ?*const bun.String) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const value = raw.BunString__toJS(globalObject, bunString);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.BunString__toJS(globalObject, bunString);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: BunString__fromUTF16Unitialized
pub extern fn BunString__fromUTF16Unitialized(length: usize) bun.String;

/// Source: BunString__fromLatin1Unitialized
pub extern fn BunString__fromLatin1Unitialized(length: usize) bun.String;

/// Source: BunString__fromLatin1
pub extern fn BunString__fromLatin1(bytes: ?[*]const u8, length: usize) bun.String;

/// Source: BunString__fromUTF16ToLatin1
pub extern fn BunString__fromUTF16ToLatin1(bytes: ?[*]const u16, length: usize) bun.String;

/// Source: BunString__fromUTF16
pub extern fn BunString__fromUTF16(bytes: ?[*]const u16, length: usize) bun.String;

/// Source: BunString__fromBytes
pub extern fn BunString__fromBytes(bytes: ?[*]const u8, length: usize) bun.String;

/// Source: BunString__toJSON
pub fn BunString__toJSON(globalObject: *jsc.JSGlobalObject, bunString: ?*bun.String) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const value = raw.BunString__toJSON(globalObject, bunString);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.BunString__toJSON(globalObject, bunString);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: BunString__toWTFString
pub extern fn BunString__toWTFString(bunString: ?*bun.String) void;

/// Source: WTFStringImpl__isThreadSafe
pub extern fn WTFStringImpl__isThreadSafe(wtf: ?*const bun.WTF._StringImplStruct) bool;

/// Source: Bun__WTFStringImpl__ensureHash
pub extern fn Bun__WTFStringImpl__ensureHash(str: ?*bun.WTF._StringImplStruct) void;

/// Source: WTF__dtoa
pub extern fn WTF__dtoa(buf_124_bytes: ?*u8, number: f64) usize;

/// Source: JSC__jsToNumber
pub extern fn JSC__jsToNumber(latin1_ptr: ?[*]const u8, len: usize) f64;

/// Source: Bun__ExposeNodeModuleGlobals
pub extern fn Bun__ExposeNodeModuleGlobals(globalObject: ?*jsc.JSGlobalObject) void;

/// Source: Bun__REPL__setupGlobalRequire
pub fn Bun__REPL__setupGlobalRequire(globalObject: *jsc.JSGlobalObject, cwdPtr: ?[*]const u8, cwdLen: usize) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.Bun__REPL__setupGlobalRequire(globalObject, cwdPtr, cwdLen);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.Bun__REPL__setupGlobalRequire(globalObject, cwdPtr, cwdLen);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: IPCSerialize
pub fn IPCSerialize(global: *jsc.JSGlobalObject, message: jsc.JSValue, handle: jsc.JSValue) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(global, @src());
        defer scope.deinit();

        const value = raw.IPCSerialize(global, message, handle);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.IPCSerialize(global, message, handle);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: IPCParse
pub fn IPCParse(global: *jsc.JSGlobalObject, target: jsc.JSValue, serialized: jsc.JSValue, fd: jsc.JSValue) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(global, @src());
        defer scope.deinit();

        const value = raw.IPCParse(global, target, serialized, fd);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.IPCParse(global, target, serialized, fd);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: Bun__HTTPServerAgent__notifyServerStarted
pub extern fn Bun__HTTPServerAgent__notifyServerStarted(agent: ?*HTTPServerAgent.InspectorHTTPServerAgent, serverId: HTTPServerAgent.ServerId, hotReloadId: HTTPServerAgent.HotReloadId, address: ?*const bun.String, startTime: f64, serverInstance: ?*anyopaque) void;

/// Source: Bun__HTTPServerAgent__notifyServerStopped
pub extern fn Bun__HTTPServerAgent__notifyServerStopped(agent: ?*HTTPServerAgent.InspectorHTTPServerAgent, serverId: HTTPServerAgent.ServerId, timestamp: f64) void;

/// Source: Bun__HTTPServerAgent__notifyServerRoutesUpdated
pub extern fn Bun__HTTPServerAgent__notifyServerRoutesUpdated(agent: ?*HTTPServerAgent.InspectorHTTPServerAgent, serverId: HTTPServerAgent.ServerId, hotReloadId: HTTPServerAgent.HotReloadId, routes_ptr: ?[*]HTTPServerAgent.Route, routes_len: usize) void;

/// Source: JSMockFunction__getCalls
pub fn JSMockFunction__getCalls(globalThis: *jsc.JSGlobalObject, encodedValue: jsc.JSValue) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(globalThis, @src());
        defer scope.deinit();

        const value = raw.JSMockFunction__getCalls(globalThis, encodedValue);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.JSMockFunction__getCalls(globalThis, encodedValue);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: JSMockFunction__getReturns
pub fn JSMockFunction__getReturns(globalThis: *jsc.JSGlobalObject, encodedValue: jsc.JSValue) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(globalThis, @src());
        defer scope.deinit();

        const value = raw.JSMockFunction__getReturns(globalThis, encodedValue);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.JSMockFunction__getReturns(globalThis, encodedValue);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: JSMock__setOverridenDateNow
pub extern fn JSMock__setOverridenDateNow(globalObject: ?*jsc.JSGlobalObject, time_ms: f64) void;

/// Source: JSMock__getCurrentUnixTimeMs
pub extern fn JSMock__getCurrentUnixTimeMs() f64;

/// Source: JSC__JSValue__toZigException
pub fn JSC__JSValue__toZigException(jsException: jsc.JSValue, global: *jsc.JSGlobalObject, exception: ?*jsc.ZigException) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(global, @src());
        defer scope.deinit();

        const result = raw.JSC__JSValue__toZigException(jsException, global, exception);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSValue__toZigException(jsException, global, exception);
        if (Bun__RETURN_IF_EXCEPTION(global)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSGlobalObject__addGc
pub extern fn JSC__JSGlobalObject__addGc(globalObject: ?*jsc.JSGlobalObject) void;

/// Source: Bun__performTask
pub fn Bun__performTask(globalObject: *jsc.JSGlobalObject, task: ?*bun.jsc.CppTask) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.Bun__performTask(globalObject, task);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.Bun__performTask(globalObject, task);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSGlobalObject__reload
pub fn JSC__JSGlobalObject__reload(arg0: *jsc.JSGlobalObject) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg0, @src());
        defer scope.deinit();

        const result = raw.JSC__JSGlobalObject__reload(arg0);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSGlobalObject__reload(arg0);
        if (Bun__RETURN_IF_EXCEPTION(arg0)) return error.JSError;
        return result;
    }
}

/// Source: WebCore__DOMURL__href_
pub extern fn WebCore__DOMURL__href_(domURL: ?*bun.DOMURL, arg1: ?*bun.jsc.ZigString) void;

/// Source: WebCore__DOMURL__pathname_
pub extern fn WebCore__DOMURL__pathname_(domURL: ?*bun.DOMURL, arg1: ?*bun.jsc.ZigString) void;

/// Source: JSC__JSObject__putRecord
pub fn JSC__JSObject__putRecord(object: ?*bun.jsc.JSObject, global: *jsc.JSGlobalObject, key: ?*bun.jsc.ZigString, values: ?[*]bun.jsc.ZigString, valuesLen: usize) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(global, @src());
        defer scope.deinit();

        const result = raw.JSC__JSObject__putRecord(object, global, key, values, valuesLen);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSObject__putRecord(object, global, key, values, valuesLen);
        if (Bun__RETURN_IF_EXCEPTION(global)) return error.JSError;
        return result;
    }
}

/// Source: ReadableStream__empty
pub fn ReadableStream__empty(globalObject: *jsc.JSGlobalObject) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const value = raw.ReadableStream__empty(globalObject);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.ReadableStream__empty(globalObject);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: ReadableStream__used
pub fn ReadableStream__used(globalObject: *jsc.JSGlobalObject) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const value = raw.ReadableStream__used(globalObject);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.ReadableStream__used(globalObject);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: ZigString__toExternalValue
pub extern fn ZigString__toExternalValue(arg0: ?*const bun.jsc.ZigString, arg1: ?*jsc.JSGlobalObject) jsc.JSValue;

/// Source: JSC__JSPromise__reject
pub fn JSC__JSPromise__reject(arg0: ?*bun.jsc.JSPromise, globalObject: *jsc.JSGlobalObject, JSValue2: jsc.JSValue) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.JSC__JSPromise__reject(arg0, globalObject, JSValue2);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSPromise__reject(arg0, globalObject, JSValue2);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSPromise__rejectAsHandled
pub fn JSC__JSPromise__rejectAsHandled(arg0: ?*bun.jsc.JSPromise, arg1: *jsc.JSGlobalObject, JSValue2: jsc.JSValue) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const result = raw.JSC__JSPromise__rejectAsHandled(arg0, arg1, JSValue2);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSPromise__rejectAsHandled(arg0, arg1, JSValue2);
        if (Bun__RETURN_IF_EXCEPTION(arg1)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSPromise__resolve
pub fn JSC__JSPromise__resolve(arg0: ?*bun.jsc.JSPromise, arg1: *jsc.JSGlobalObject, JSValue2: jsc.JSValue) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const result = raw.JSC__JSPromise__resolve(arg0, arg1, JSValue2);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSPromise__resolve(arg0, arg1, JSValue2);
        if (Bun__RETURN_IF_EXCEPTION(arg1)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSPromise__result
pub extern fn JSC__JSPromise__result(promise: ?*bun.jsc.JSPromise, arg1: ?*jsc.VM) jsc.JSValue;

/// Source: JSC__JSPromise__status
pub extern fn JSC__JSPromise__status(arg0: ?*const bun.jsc.JSPromise) u32;

/// Source: JSC__JSPromise__isHandled
pub extern fn JSC__JSPromise__isHandled(arg0: ?*const bun.jsc.JSPromise) bool;

/// Source: JSC__JSPromise__setHandled
pub extern fn JSC__JSPromise__setHandled(promise: ?*bun.jsc.JSPromise) void;

/// Source: JSC__JSInternalPromise__reject
pub fn JSC__JSInternalPromise__reject(arg0: ?*bun.jsc.JSPromise, globalObject: *jsc.JSGlobalObject, JSValue2: jsc.JSValue) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.JSC__JSInternalPromise__reject(arg0, globalObject, JSValue2);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSInternalPromise__reject(arg0, globalObject, JSValue2);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSInternalPromise__resolve
pub fn JSC__JSInternalPromise__resolve(arg0: ?*bun.jsc.JSPromise, arg1: *jsc.JSGlobalObject, JSValue2: jsc.JSValue) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const result = raw.JSC__JSInternalPromise__resolve(arg0, arg1, JSValue2);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSInternalPromise__resolve(arg0, arg1, JSValue2);
        if (Bun__RETURN_IF_EXCEPTION(arg1)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSValue__isAnyInt
pub extern fn JSC__JSValue__isAnyInt(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isBigInt
pub extern fn JSC__JSValue__isBigInt(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isBigInt32
pub extern fn JSC__JSValue__isBigInt32(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__putMayBeIndex
pub fn JSC__JSValue__putMayBeIndex(target: jsc.JSValue, globalObject: *jsc.JSGlobalObject, key: ?*const bun.String, value: jsc.JSValue) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.JSC__JSValue__putMayBeIndex(target, globalObject, key, value);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSValue__putMayBeIndex(target, globalObject, key, value);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSValue__isCell
pub extern fn JSC__JSValue__isCell(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isCustomGetterSetter
pub extern fn JSC__JSValue__isCustomGetterSetter(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isCallable
pub extern fn JSC__JSValue__isCallable(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isGetterSetter
pub extern fn JSC__JSValue__isGetterSetter(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isHeapBigInt
pub extern fn JSC__JSValue__isHeapBigInt(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isInt32
pub extern fn JSC__JSValue__isInt32(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isInt32AsAnyInt
pub extern fn JSC__JSValue__isInt32AsAnyInt(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isNull
pub extern fn JSC__JSValue__isNull(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isNumber
pub extern fn JSC__JSValue__isNumber(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isObject
pub extern fn JSC__JSValue__isObject(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isPrimitive
pub extern fn JSC__JSValue__isPrimitive(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isSymbol
pub extern fn JSC__JSValue__isSymbol(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isUInt32AsAnyInt
pub extern fn JSC__JSValue__isUInt32AsAnyInt(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isUndefined
pub extern fn JSC__JSValue__isUndefined(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__isUndefinedOrNull
pub extern fn JSC__JSValue__isUndefinedOrNull(JSValue0: jsc.JSValue) bool;

/// Source: JSC__JSValue__jsEmptyString
pub extern fn JSC__JSValue__jsEmptyString(arg0: ?*jsc.JSGlobalObject) jsc.JSValue;

/// Source: JSC__JSValue__jsNumberFromChar
pub extern fn JSC__JSValue__jsNumberFromChar(arg0: u8) jsc.JSValue;

/// Source: JSC__JSValue__jsNumberFromU16
pub extern fn JSC__JSValue__jsNumberFromU16(arg0: u16) jsc.JSValue;

/// Source: JSC__JSValue__toInt64
pub extern fn JSC__JSValue__toInt64(val: jsc.JSValue) i64;

/// Source: JSC__JSValue__getIfPropertyExistsImpl
pub fn JSC__JSValue__getIfPropertyExistsImpl(JSValue0: jsc.JSValue, globalObject: *jsc.JSGlobalObject, arg1: ?[*]const u8, arg2: usize) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const value = raw.JSC__JSValue__getIfPropertyExistsImpl(JSValue0, globalObject, arg1, arg2);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.JSC__JSValue__getIfPropertyExistsImpl(JSValue0, globalObject, arg1, arg2);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: JSC__JSValue__coerceToInt32
pub fn JSC__JSValue__coerceToInt32(JSValue0: jsc.JSValue, arg1: *jsc.JSGlobalObject) error{JSError}!i32 {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const result = raw.JSC__JSValue__coerceToInt32(JSValue0, arg1);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSValue__coerceToInt32(JSValue0, arg1);
        if (Bun__RETURN_IF_EXCEPTION(arg1)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSValue__coerceToInt64
pub fn JSC__JSValue__coerceToInt64(JSValue0: jsc.JSValue, arg1: *jsc.JSGlobalObject) error{JSError}!i64 {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const result = raw.JSC__JSValue__coerceToInt64(JSValue0, arg1);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSValue__coerceToInt64(JSValue0, arg1);
        if (Bun__RETURN_IF_EXCEPTION(arg1)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSValue__jsTDZValue
pub extern fn JSC__JSValue__jsTDZValue() jsc.JSValue;

/// Source: JSC__JSValue__toStringOrNull
pub fn JSC__JSValue__toStringOrNull(JSValue0: jsc.JSValue, arg1: *jsc.JSGlobalObject) error{JSError}!*bun.jsc.JSString {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const value = raw.JSC__JSValue__toStringOrNull(JSValue0, arg1);
        scope.assertExceptionPresenceMatches(value == null);
        return if (value == null) error.JSError else value.?;
    } else {
        const value = raw.JSC__JSValue__toStringOrNull(JSValue0, arg1);
        if (value == null) return error.JSError;
        return value.?;
    }
}

/// Source: JSC__JSValue__toMatch
pub fn JSC__JSValue__toMatch(regexValue: jsc.JSValue, global: *jsc.JSGlobalObject, value: jsc.JSValue) error{JSError}!bool {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(global, @src());
        defer scope.deinit();

        const result = raw.JSC__JSValue__toMatch(regexValue, global, value);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSValue__toMatch(regexValue, global, value);
        if (Bun__RETURN_IF_EXCEPTION(global)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSValue__getName
pub fn JSC__JSValue__getName(JSValue0: jsc.JSValue, globalObject: *jsc.JSGlobalObject, arg2: ?*bun.String) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.JSC__JSValue__getName(JSValue0, globalObject, arg2);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSValue__getName(JSValue0, globalObject, arg2);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: JSC__VM__isJITEnabled
pub extern fn JSC__VM__isJITEnabled() bool;

/// Source: JSC__VM__isTerminationException
pub extern fn JSC__VM__isTerminationException(vm: ?*jsc.VM, exception: ?*bun.jsc.Exception) bool;

/// Source: JSC__VM__clearHasTerminationRequest
pub extern fn JSC__VM__clearHasTerminationRequest(vm: ?*jsc.VM) void;

/// Source: JSC__VM__hasTerminationRequest
pub extern fn JSC__VM__hasTerminationRequest(vm: ?*jsc.VM) bool;

/// Source: JSC__JSValue__forEachProperty
pub fn JSC__JSValue__forEachProperty(JSValue0: jsc.JSValue, globalObject: *jsc.JSGlobalObject, arg2: ?*anyopaque, iter: ?*const fn(arg0: *jsc.JSGlobalObject, ctx: ?*anyopaque, arg2: *bun.jsc.ZigString, JSValue3: jsc.JSValue, isSymbol: bool, isPrivateSymbol: bool) callconv(.c) void) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.JSC__JSValue__forEachProperty(JSValue0, globalObject, arg2, iter);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSValue__forEachProperty(JSValue0, globalObject, arg2, iter);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: JSC__isBigIntInUInt64Range
pub extern fn JSC__isBigIntInUInt64Range(value: jsc.JSValue, max: u64, min: u64) bool;

/// Source: JSC__isBigIntInInt64Range
pub extern fn JSC__isBigIntInInt64Range(value: jsc.JSValue, max: i64, min: i64) bool;

/// Source: JSC__JSValue__forEachPropertyOrdered
pub fn JSC__JSValue__forEachPropertyOrdered(JSValue0: jsc.JSValue, globalObject: *jsc.JSGlobalObject, arg2: ?*anyopaque, iter: ?*const fn(arg0: *jsc.JSGlobalObject, ctx: ?*anyopaque, arg2: *bun.jsc.ZigString, JSValue3: jsc.JSValue, isSymbol: bool, isPrivateSymbol: bool) callconv(.c) void) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.JSC__JSValue__forEachPropertyOrdered(JSValue0, globalObject, arg2, iter);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSValue__forEachPropertyOrdered(JSValue0, globalObject, arg2, iter);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSValue__isConstructor
pub extern fn JSC__JSValue__isConstructor(JSValue0: jsc.JSValue) bool;

/// Source: Bun__parseDate
pub fn Bun__parseDate(globalObject: *jsc.JSGlobalObject, str: ?*bun.String) error{JSError}!f64 {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.Bun__parseDate(globalObject, str);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.Bun__parseDate(globalObject, str);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: Bun__gregorianDateTimeToMS
pub fn Bun__gregorianDateTimeToMS(globalObject: *jsc.JSGlobalObject, year: c_int, month: c_int, day: c_int, hour: c_int, minute: c_int, second: c_int, millisecond: c_int, localTime: bool) error{JSError}!f64 {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.Bun__gregorianDateTimeToMS(globalObject, year, month, day, hour, minute, second, millisecond, localTime);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.Bun__gregorianDateTimeToMS(globalObject, year, month, day, hour, minute, second, millisecond, localTime);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: Bun__msToGregorianDateTime
pub extern fn Bun__msToGregorianDateTime(globalObject: ?*jsc.JSGlobalObject, ms: f64, localTime: bool, year: ?*c_int, month: ?*c_int, day: ?*c_int, hour: ?*c_int, minute: ?*c_int, second: ?*c_int, weekday: ?*c_int) void;

/// Source: JSC__JSMap__create
pub extern fn JSC__JSMap__create(arg0: ?*jsc.JSGlobalObject) jsc.JSValue;

/// Source: JSC__JSMap__get
pub fn JSC__JSMap__get(map: ?*bun.jsc.JSMap, arg1: *jsc.JSGlobalObject, JSValue2: jsc.JSValue) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const value = raw.JSC__JSMap__get(map, arg1, JSValue2);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.JSC__JSMap__get(map, arg1, JSValue2);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: JSC__JSMap__has
pub fn JSC__JSMap__has(map: ?*bun.jsc.JSMap, arg1: *jsc.JSGlobalObject, JSValue2: jsc.JSValue) error{JSError}!bool {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const result = raw.JSC__JSMap__has(map, arg1, JSValue2);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSMap__has(map, arg1, JSValue2);
        if (Bun__RETURN_IF_EXCEPTION(arg1)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSMap__remove
pub fn JSC__JSMap__remove(map: ?*bun.jsc.JSMap, arg1: *jsc.JSGlobalObject, JSValue2: jsc.JSValue) error{JSError}!bool {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const result = raw.JSC__JSMap__remove(map, arg1, JSValue2);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSMap__remove(map, arg1, JSValue2);
        if (Bun__RETURN_IF_EXCEPTION(arg1)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSMap__clear
pub fn JSC__JSMap__clear(map: ?*bun.jsc.JSMap, arg1: *jsc.JSGlobalObject) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const result = raw.JSC__JSMap__clear(map, arg1);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSMap__clear(map, arg1);
        if (Bun__RETURN_IF_EXCEPTION(arg1)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSMap__set
pub fn JSC__JSMap__set(map: ?*bun.jsc.JSMap, arg1: *jsc.JSGlobalObject, JSValue2: jsc.JSValue, JSValue3: jsc.JSValue) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const result = raw.JSC__JSMap__set(map, arg1, JSValue2, JSValue3);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSMap__set(map, arg1, JSValue2, JSValue3);
        if (Bun__RETURN_IF_EXCEPTION(arg1)) return error.JSError;
        return result;
    }
}

/// Source: JSC__JSMap__size
pub fn JSC__JSMap__size(map: ?*bun.jsc.JSMap, arg1: *jsc.JSGlobalObject) error{JSError}!u32 {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(arg1, @src());
        defer scope.deinit();

        const result = raw.JSC__JSMap__size(map, arg1);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.JSC__JSMap__size(map, arg1);
        if (Bun__RETURN_IF_EXCEPTION(arg1)) return error.JSError;
        return result;
    }
}

/// Source: JSC__CustomGetterSetter__isGetterNull
pub extern fn JSC__CustomGetterSetter__isGetterNull(gettersetter: ?*bun.jsc.CustomGetterSetter) bool;

/// Source: JSC__CustomGetterSetter__isSetterNull
pub extern fn JSC__CustomGetterSetter__isSetterNull(gettersetter: ?*bun.jsc.CustomGetterSetter) bool;

/// Source: JSC__SourceProvider__deref
pub extern fn JSC__SourceProvider__deref(provider: ?*bun.jsc.SourceProvider) void;

/// Source: Bun__RETURN_IF_EXCEPTION
pub extern fn Bun__RETURN_IF_EXCEPTION(globalObject: ?*jsc.JSGlobalObject) bool;

/// Source: Bun__JSValue__bind
pub fn Bun__JSValue__bind(functionToBindEncoded: jsc.JSValue, globalObject: *jsc.JSGlobalObject, bindThisArgEncoded: jsc.JSValue, name: ?*const bun.String, length: f64, args: ?[*]jsc.JSValue, args_len: usize) error{JSError}!jsc.JSValue {
    if (comptime Environment.ci_assert) {
        var scope: jsc.ExceptionValidationScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const value = raw.Bun__JSValue__bind(functionToBindEncoded, globalObject, bindThisArgEncoded, name, length, args, args_len);
        scope.assertExceptionPresenceMatches(value == .zero);
        return if (value == .zero) error.JSError else value;
    } else {
        const value = raw.Bun__JSValue__bind(functionToBindEncoded, globalObject, bindThisArgEncoded, name, length, args, args_len);
        if (value == .zero) return error.JSError;
        return value;
    }
}

/// Source: Bun__JSValue__setPrototypeDirect
pub fn Bun__JSValue__setPrototypeDirect(valueEncoded: jsc.JSValue, prototypeEncoded: jsc.JSValue, globalObject: *jsc.JSGlobalObject) error{JSError}!void {
    if (comptime Environment.ci_assert) {
        var scope: jsc.TopExceptionScope = undefined;
        scope.init(globalObject, @src());
        defer scope.deinit();

        const result = raw.Bun__JSValue__setPrototypeDirect(valueEncoded, prototypeEncoded, globalObject);
        try scope.returnIfException();
        return result;
    } else {
        const result = raw.Bun__JSValue__setPrototypeDirect(valueEncoded, prototypeEncoded, globalObject);
        if (Bun__RETURN_IF_EXCEPTION(globalObject)) return error.JSError;
        return result;
    }
}

/// Source: Bun__CallFrame__getLineNumber
pub extern fn Bun__CallFrame__getLineNumber(callFrame: ?*bun.jsc.CallFrame, globalObject: ?*jsc.JSGlobalObject) c_uint;

/// Source: Bun__ramSize
pub extern fn Bun__ramSize() usize;

/// Source: Bun__StackCheck__initialize
pub extern fn Bun__StackCheck__initialize() void;

/// Source: Bun__StackCheck__getMaxStack
pub extern fn Bun__StackCheck__getMaxStack() ?*anyopaque;

const raw = struct {
    extern fn BunString__createUTF8ForJS(globalObject: ?*jsc.JSGlobalObject, ptr: ?[*]const u8, length: usize) jsc.JSValue;
    extern fn BunString__transferToJS(bunString: ?*bun.String, globalObject: ?*jsc.JSGlobalObject) jsc.JSValue;
    extern fn BunString__toJS(globalObject: ?*jsc.JSGlobalObject, bunString: ?*const bun.String) jsc.JSValue;
    extern fn BunString__toJSON(globalObject: ?*jsc.JSGlobalObject, bunString: ?*bun.String) jsc.JSValue;
    extern fn Bun__REPL__setupGlobalRequire(globalObject: ?*jsc.JSGlobalObject, cwdPtr: ?[*]const u8, cwdLen: usize) void;
    extern fn IPCSerialize(global: ?*jsc.JSGlobalObject, message: jsc.JSValue, handle: jsc.JSValue) jsc.JSValue;
    extern fn IPCParse(global: ?*jsc.JSGlobalObject, target: jsc.JSValue, serialized: jsc.JSValue, fd: jsc.JSValue) jsc.JSValue;
    extern fn JSMockFunction__getCalls(globalThis: ?*jsc.JSGlobalObject, encodedValue: jsc.JSValue) jsc.JSValue;
    extern fn JSMockFunction__getReturns(globalThis: ?*jsc.JSGlobalObject, encodedValue: jsc.JSValue) jsc.JSValue;
    extern fn JSC__JSValue__toZigException(jsException: jsc.JSValue, global: ?*jsc.JSGlobalObject, exception: ?*jsc.ZigException) void;
    extern fn Bun__performTask(globalObject: ?*jsc.JSGlobalObject, task: ?*bun.jsc.CppTask) void;
    extern fn JSC__JSGlobalObject__reload(arg0: ?*jsc.JSGlobalObject) void;
    extern fn JSC__JSObject__putRecord(object: ?*bun.jsc.JSObject, global: ?*jsc.JSGlobalObject, key: ?*bun.jsc.ZigString, values: ?[*]bun.jsc.ZigString, valuesLen: usize) void;
    extern fn ReadableStream__empty(globalObject: ?*jsc.JSGlobalObject) jsc.JSValue;
    extern fn ReadableStream__used(globalObject: ?*jsc.JSGlobalObject) jsc.JSValue;
    extern fn JSC__JSPromise__reject(arg0: ?*bun.jsc.JSPromise, globalObject: ?*jsc.JSGlobalObject, JSValue2: jsc.JSValue) void;
    extern fn JSC__JSPromise__rejectAsHandled(arg0: ?*bun.jsc.JSPromise, arg1: ?*jsc.JSGlobalObject, JSValue2: jsc.JSValue) void;
    extern fn JSC__JSPromise__resolve(arg0: ?*bun.jsc.JSPromise, arg1: ?*jsc.JSGlobalObject, JSValue2: jsc.JSValue) void;
    extern fn JSC__JSInternalPromise__reject(arg0: ?*bun.jsc.JSPromise, globalObject: ?*jsc.JSGlobalObject, JSValue2: jsc.JSValue) void;
    extern fn JSC__JSInternalPromise__resolve(arg0: ?*bun.jsc.JSPromise, arg1: ?*jsc.JSGlobalObject, JSValue2: jsc.JSValue) void;
    extern fn JSC__JSValue__putMayBeIndex(target: jsc.JSValue, globalObject: ?*jsc.JSGlobalObject, key: ?*const bun.String, value: jsc.JSValue) void;
    extern fn JSC__JSValue__getIfPropertyExistsImpl(JSValue0: jsc.JSValue, globalObject: ?*jsc.JSGlobalObject, arg1: ?[*]const u8, arg2: usize) jsc.JSValue;
    extern fn JSC__JSValue__coerceToInt32(JSValue0: jsc.JSValue, arg1: ?*jsc.JSGlobalObject) i32;
    extern fn JSC__JSValue__coerceToInt64(JSValue0: jsc.JSValue, arg1: ?*jsc.JSGlobalObject) i64;
    extern fn JSC__JSValue__toStringOrNull(JSValue0: jsc.JSValue, arg1: ?*jsc.JSGlobalObject) ?*bun.jsc.JSString;
    extern fn JSC__JSValue__toMatch(regexValue: jsc.JSValue, global: ?*jsc.JSGlobalObject, value: jsc.JSValue) bool;
    extern fn JSC__JSValue__getName(JSValue0: jsc.JSValue, globalObject: ?*jsc.JSGlobalObject, arg2: ?*bun.String) void;
    extern fn JSC__JSValue__forEachProperty(JSValue0: jsc.JSValue, globalObject: ?*jsc.JSGlobalObject, arg2: ?*anyopaque, iter: ?*const fn(arg0: *jsc.JSGlobalObject, ctx: ?*anyopaque, arg2: *bun.jsc.ZigString, JSValue3: jsc.JSValue, isSymbol: bool, isPrivateSymbol: bool) callconv(.c) void) void;
    extern fn JSC__JSValue__forEachPropertyOrdered(JSValue0: jsc.JSValue, globalObject: ?*jsc.JSGlobalObject, arg2: ?*anyopaque, iter: ?*const fn(arg0: *jsc.JSGlobalObject, ctx: ?*anyopaque, arg2: *bun.jsc.ZigString, JSValue3: jsc.JSValue, isSymbol: bool, isPrivateSymbol: bool) callconv(.c) void) void;
    extern fn Bun__parseDate(globalObject: ?*jsc.JSGlobalObject, str: ?*bun.String) f64;
    extern fn Bun__gregorianDateTimeToMS(globalObject: ?*jsc.JSGlobalObject, year: c_int, month: c_int, day: c_int, hour: c_int, minute: c_int, second: c_int, millisecond: c_int, localTime: bool) f64;
    extern fn JSC__JSMap__get(map: ?*bun.jsc.JSMap, arg1: ?*jsc.JSGlobalObject, JSValue2: jsc.JSValue) jsc.JSValue;
    extern fn JSC__JSMap__has(map: ?*bun.jsc.JSMap, arg1: ?*jsc.JSGlobalObject, JSValue2: jsc.JSValue) bool;
    extern fn JSC__JSMap__remove(map: ?*bun.jsc.JSMap, arg1: ?*jsc.JSGlobalObject, JSValue2: jsc.JSValue) bool;
    extern fn JSC__JSMap__clear(map: ?*bun.jsc.JSMap, arg1: ?*jsc.JSGlobalObject) void;
    extern fn JSC__JSMap__set(map: ?*bun.jsc.JSMap, arg1: ?*jsc.JSGlobalObject, JSValue2: jsc.JSValue, JSValue3: jsc.JSValue) void;
    extern fn JSC__JSMap__size(map: ?*bun.jsc.JSMap, arg1: ?*jsc.JSGlobalObject) u32;
    extern fn Bun__JSValue__bind(functionToBindEncoded: jsc.JSValue, globalObject: ?*jsc.JSGlobalObject, bindThisArgEncoded: jsc.JSValue, name: ?*const bun.String, length: f64, args: ?[*]jsc.JSValue, args_len: usize) jsc.JSValue;
    extern fn Bun__JSValue__setPrototypeDirect(valueEncoded: jsc.JSValue, prototypeEncoded: jsc.JSValue, globalObject: ?*jsc.JSGlobalObject) void;
};
