// Generated by: src/codegen/generate-node-errors.ts
const std = @import("std");
const bun = @import("bun");
const jsc = bun.jsc;

pub fn ErrorBuilder(comptime code: Error, comptime fmt: [:0]const u8, Args: type) type {
  return struct {
      global: *jsc.JSGlobalObject,
      args: Args,

      // Throw this error as a JS exception
      pub inline fn throw(this: @This()) bun.JSError {
        return code.throw(this.global, fmt, this.args);
      }

      /// Turn this into a JSValue
      pub inline fn toJS(this: @This()) jsc.JSValue {
        return code.fmt(this.global, fmt, this.args);
      }

      /// Turn this into a JSPromise that is already rejected.
      pub inline fn reject(this: @This()) jsc.JSValue {
        return jsc.JSPromise.rejectedPromise(this.global, code.fmt(this.global, fmt, this.args)).toJS();
      }
  };
}

pub const Error = enum(u16) {

    /// AbortError: ABORT_ERR (instanceof Error)
    ABORT_ERR = 0,
    /// Error: ERR_ACCESS_DENIED (instanceof Error)
    ACCESS_DENIED = 1,
    /// TypeError: ERR_AMBIGUOUS_ARGUMENT (instanceof TypeError)
    AMBIGUOUS_ARGUMENT = 2,
    /// TypeError: ERR_ARG_NOT_ITERABLE (instanceof TypeError)
    ARG_NOT_ITERABLE = 3,
    /// Error: ERR_ASSERTION (instanceof Error)
    ASSERTION = 4,
    /// TypeError: ERR_ASYNC_CALLBACK (instanceof TypeError)
    ASYNC_CALLBACK = 5,
    /// TypeError: ERR_ASYNC_TYPE (instanceof TypeError)
    ASYNC_TYPE = 6,
    /// TypeError: ERR_BODY_ALREADY_USED (instanceof TypeError)
    BODY_ALREADY_USED = 7,
    /// Error: ERR_BORINGSSL (instanceof Error)
    BORINGSSL = 8,
    /// Error: ERR_ZSTD (instanceof Error)
    ZSTD = 9,
    /// RangeError: ERR_BROTLI_INVALID_PARAM (instanceof RangeError)
    BROTLI_INVALID_PARAM = 10,
    /// Error: ERR_BUFFER_CONTEXT_NOT_AVAILABLE (instanceof Error)
    BUFFER_CONTEXT_NOT_AVAILABLE = 11,
    /// RangeError: ERR_BUFFER_OUT_OF_BOUNDS (instanceof RangeError)
    BUFFER_OUT_OF_BOUNDS = 12,
    /// RangeError: ERR_BUFFER_TOO_LARGE (instanceof RangeError)
    BUFFER_TOO_LARGE = 13,
    /// Error: ERR_CHILD_PROCESS_IPC_REQUIRED (instanceof Error)
    CHILD_PROCESS_IPC_REQUIRED = 14,
    /// RangeError: ERR_CHILD_PROCESS_STDIO_MAXBUFFER (instanceof RangeError)
    CHILD_PROCESS_STDIO_MAXBUFFER = 15,
    /// Error: ERR_CLOSED_MESSAGE_PORT (instanceof Error)
    CLOSED_MESSAGE_PORT = 16,
    /// TypeError: ERR_CONSOLE_WRITABLE_STREAM (instanceof TypeError)
    CONSOLE_WRITABLE_STREAM = 17,
    /// TypeError: ERR_CONSTRUCT_CALL_INVALID (instanceof TypeError)
    CONSTRUCT_CALL_INVALID = 18,
    /// TypeError: ERR_CONSTRUCT_CALL_REQUIRED (instanceof TypeError)
    CONSTRUCT_CALL_REQUIRED = 19,
    /// Error: ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED (instanceof Error)
    CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED = 20,
    /// TypeError: ERR_CRYPTO_ECDH_INVALID_FORMAT (instanceof TypeError)
    CRYPTO_ECDH_INVALID_FORMAT = 21,
    /// Error: ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY (instanceof Error)
    CRYPTO_ECDH_INVALID_PUBLIC_KEY = 22,
    /// Error: ERR_CRYPTO_HASH_FINALIZED (instanceof Error)
    CRYPTO_HASH_FINALIZED = 23,
    /// Error: ERR_CRYPTO_HASH_UPDATE_FAILED (instanceof Error)
    CRYPTO_HASH_UPDATE_FAILED = 24,
    /// Error: ERR_CRYPTO_INCOMPATIBLE_KEY_OPTIONS (instanceof Error)
    CRYPTO_INCOMPATIBLE_KEY_OPTIONS = 25,
    /// Error: ERR_CRYPTO_INCOMPATIBLE_KEY (instanceof Error)
    CRYPTO_INCOMPATIBLE_KEY = 26,
    /// Error: ERR_CRYPTO_INITIALIZATION_FAILED (instanceof Error)
    CRYPTO_INITIALIZATION_FAILED = 27,
    /// TypeError: ERR_CRYPTO_INVALID_AUTH_TAG (instanceof TypeError)
    CRYPTO_INVALID_AUTH_TAG = 28,
    /// TypeError: ERR_CRYPTO_INVALID_COUNTER (instanceof TypeError)
    CRYPTO_INVALID_COUNTER = 29,
    /// TypeError: ERR_CRYPTO_INVALID_CURVE (instanceof TypeError)
    CRYPTO_INVALID_CURVE = 30,
    /// TypeError: ERR_CRYPTO_INVALID_DIGEST (instanceof TypeError)
    CRYPTO_INVALID_DIGEST = 31,
    /// TypeError: ERR_CRYPTO_INVALID_IV (instanceof TypeError)
    CRYPTO_INVALID_IV = 32,
    /// TypeError: ERR_CRYPTO_INVALID_JWK (instanceof TypeError)
    CRYPTO_INVALID_JWK = 33,
    /// TypeError: ERR_CRYPTO_INVALID_KEY_OBJECT_TYPE (instanceof TypeError)
    CRYPTO_INVALID_KEY_OBJECT_TYPE = 34,
    /// RangeError: ERR_CRYPTO_INVALID_KEYLEN (instanceof RangeError)
    CRYPTO_INVALID_KEYLEN = 35,
    /// RangeError: ERR_CRYPTO_INVALID_KEYPAIR (instanceof RangeError)
    CRYPTO_INVALID_KEYPAIR = 36,
    /// RangeError: ERR_CRYPTO_INVALID_KEYTYPE (instanceof RangeError)
    CRYPTO_INVALID_KEYTYPE = 37,
    /// RangeError: ERR_CRYPTO_INVALID_MESSAGELEN (instanceof RangeError)
    CRYPTO_INVALID_MESSAGELEN = 38,
    /// RangeError: ERR_CRYPTO_INVALID_SCRYPT_PARAMS (instanceof RangeError)
    CRYPTO_INVALID_SCRYPT_PARAMS = 39,
    /// Error: ERR_CRYPTO_INVALID_STATE (instanceof Error)
    CRYPTO_INVALID_STATE = 40,
    /// RangeError: ERR_CRYPTO_INVALID_TAG_LENGTH (instanceof RangeError)
    CRYPTO_INVALID_TAG_LENGTH = 41,
    /// Error: ERR_CRYPTO_JOB_INIT_FAILED (instanceof Error)
    CRYPTO_JOB_INIT_FAILED = 42,
    /// Error: ERR_CRYPTO_JWK_UNSUPPORTED_CURVE (instanceof Error)
    CRYPTO_JWK_UNSUPPORTED_CURVE = 43,
    /// Error: ERR_CRYPTO_JWK_UNSUPPORTED_KEY_TYPE (instanceof Error)
    CRYPTO_JWK_UNSUPPORTED_KEY_TYPE = 44,
    /// Error: ERR_CRYPTO_OPERATION_FAILED (instanceof Error)
    CRYPTO_OPERATION_FAILED = 45,
    /// Error: ERR_CRYPTO_SCRYPT_INVALID_PARAMETER (instanceof Error)
    CRYPTO_SCRYPT_INVALID_PARAMETER = 46,
    /// Error: ERR_CRYPTO_SIGN_KEY_REQUIRED (instanceof Error)
    CRYPTO_SIGN_KEY_REQUIRED = 47,
    /// RangeError: ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH (instanceof RangeError)
    CRYPTO_TIMING_SAFE_EQUAL_LENGTH = 48,
    /// Error: ERR_CRYPTO_UNKNOWN_CIPHER (instanceof Error)
    CRYPTO_UNKNOWN_CIPHER = 49,
    /// Error: ERR_CRYPTO_UNKNOWN_DH_GROUP (instanceof Error)
    CRYPTO_UNKNOWN_DH_GROUP = 50,
    /// Error: ERR_CRYPTO_UNSUPPORTED_OPERATION (instanceof Error)
    CRYPTO_UNSUPPORTED_OPERATION = 51,
    /// Error: ERR_DIR_CLOSED (instanceof Error)
    DIR_CLOSED = 52,
    /// Error: ERR_DLOPEN_DISABLED (instanceof Error)
    DLOPEN_DISABLED = 53,
    /// Error: ERR_DLOPEN_FAILED (instanceof Error)
    DLOPEN_FAILED = 54,
    /// Error: ERR_DNS_SET_SERVERS_FAILED (instanceof Error)
    DNS_SET_SERVERS_FAILED = 55,
    /// TypeError: ERR_ENCODING_INVALID_ENCODED_DATA (instanceof TypeError)
    ENCODING_INVALID_ENCODED_DATA = 56,
    /// RangeError: ERR_ENCODING_NOT_SUPPORTED (instanceof RangeError)
    ENCODING_NOT_SUPPORTED = 57,
    /// Error: ERR_EVENT_RECURSION (instanceof Error)
    EVENT_RECURSION = 58,
    /// Error: ERR_EXECUTION_ENVIRONMENT_NOT_AVAILABLE (instanceof Error)
    EXECUTION_ENVIRONMENT_NOT_AVAILABLE = 59,
    /// TypeError: ERR_FEATURE_UNAVAILABLE_ON_PLATFORM (instanceof TypeError)
    FEATURE_UNAVAILABLE_ON_PLATFORM = 60,
    /// TypeError: ERR_FORMDATA_PARSE_ERROR (instanceof TypeError)
    FORMDATA_PARSE_ERROR = 61,
    /// Error: ERR_FS_CP_DIR_TO_NON_DIR (instanceof Error)
    FS_CP_DIR_TO_NON_DIR = 62,
    /// Error: ERR_FS_CP_EINVAL (instanceof Error)
    FS_CP_EINVAL = 63,
    /// Error: ERR_FS_CP_FIFO_PIPE (instanceof Error)
    FS_CP_FIFO_PIPE = 64,
    /// Error: ERR_FS_CP_NON_DIR_TO_DIR (instanceof Error)
    FS_CP_NON_DIR_TO_DIR = 65,
    /// Error: ERR_FS_CP_SOCKET (instanceof Error)
    FS_CP_SOCKET = 66,
    /// Error: ERR_FS_CP_UNKNOWN (instanceof Error)
    FS_CP_UNKNOWN = 67,
    /// Error: ERR_FS_EISDIR (instanceof Error)
    FS_EISDIR = 68,
    /// Error: ERR_HTTP_BODY_NOT_ALLOWED (instanceof Error)
    HTTP_BODY_NOT_ALLOWED = 69,
    /// Error: ERR_HTTP_HEADERS_SENT (instanceof Error)
    HTTP_HEADERS_SENT = 70,
    /// Error: ERR_HTTP_CONTENT_LENGTH_MISMATCH (instanceof Error)
    HTTP_CONTENT_LENGTH_MISMATCH = 71,
    /// TypeError: ERR_HTTP_INVALID_HEADER_VALUE (instanceof TypeError)
    HTTP_INVALID_HEADER_VALUE = 72,
    /// RangeError: ERR_HTTP_INVALID_STATUS_CODE (instanceof RangeError)
    HTTP_INVALID_STATUS_CODE = 73,
    /// Error: ERR_HTTP_TRAILER_INVALID (instanceof Error)
    HTTP_TRAILER_INVALID = 74,
    /// Error: ERR_HTTP_SOCKET_ASSIGNED (instanceof Error)
    HTTP_SOCKET_ASSIGNED = 75,
    /// TypeError: ERR_HTTP2_ALTSVC_INVALID_ORIGIN (instanceof TypeError)
    HTTP2_ALTSVC_INVALID_ORIGIN = 76,
    /// TypeError: ERR_HTTP2_ALTSVC_LENGTH (instanceof TypeError)
    HTTP2_ALTSVC_LENGTH = 77,
    /// Error: ERR_HTTP2_CONNECT_AUTHORITY (instanceof Error)
    HTTP2_CONNECT_AUTHORITY = 78,
    /// Error: ERR_HTTP2_CONNECT_SCHEME (instanceof Error)
    HTTP2_CONNECT_SCHEME = 79,
    /// Error: ERR_HTTP2_CONNECT_PATH (instanceof Error)
    HTTP2_CONNECT_PATH = 80,
    /// Error: ERR_HTTP2_ERROR (instanceof Error)
    HTTP2_ERROR = 81,
    /// TypeError: ERR_HTTP2_HEADER_SINGLE_VALUE (instanceof TypeError)
    HTTP2_HEADER_SINGLE_VALUE = 82,
    /// Error: ERR_HTTP2_HEADERS_AFTER_RESPOND (instanceof Error)
    HTTP2_HEADERS_AFTER_RESPOND = 83,
    /// Error: ERR_HTTP2_HEADERS_SENT (instanceof Error)
    HTTP2_HEADERS_SENT = 84,
    /// RangeError: ERR_HTTP2_INFO_STATUS_NOT_ALLOWED (instanceof RangeError)
    HTTP2_INFO_STATUS_NOT_ALLOWED = 85,
    /// TypeError: ERR_HTTP2_INVALID_HEADER_VALUE (instanceof TypeError)
    HTTP2_INVALID_HEADER_VALUE = 86,
    /// RangeError: ERR_HTTP2_INVALID_INFO_STATUS (instanceof RangeError)
    HTTP2_INVALID_INFO_STATUS = 87,
    /// TypeError: ERR_HTTP2_INVALID_ORIGIN (instanceof TypeError)
    HTTP2_INVALID_ORIGIN = 88,
    /// TypeError: ERR_HTTP2_INVALID_PSEUDOHEADER (instanceof TypeError)
    HTTP2_INVALID_PSEUDOHEADER = 89,
    /// Error: ERR_HTTP2_INVALID_SESSION (instanceof Error)
    HTTP2_INVALID_SESSION = 90,
    /// Error: ERR_HTTP2_INVALID_STREAM (instanceof Error)
    HTTP2_INVALID_STREAM = 91,
    /// Error: ERR_HTTP2_MAX_PENDING_SETTINGS_ACK (instanceof Error)
    HTTP2_MAX_PENDING_SETTINGS_ACK = 92,
    /// Error: ERR_HTTP2_NO_SOCKET_MANIPULATION (instanceof Error)
    HTTP2_NO_SOCKET_MANIPULATION = 93,
    /// TypeError: ERR_HTTP2_ORIGIN_LENGTH (instanceof TypeError)
    HTTP2_ORIGIN_LENGTH = 94,
    /// Error: ERR_HTTP2_OUT_OF_STREAMS (instanceof Error)
    HTTP2_OUT_OF_STREAMS = 95,
    /// Error: ERR_HTTP2_PAYLOAD_FORBIDDEN (instanceof Error)
    HTTP2_PAYLOAD_FORBIDDEN = 96,
    /// Error: ERR_HTTP2_PING_CANCEL (instanceof Error)
    HTTP2_PING_CANCEL = 97,
    /// RangeError: ERR_HTTP2_PING_LENGTH (instanceof RangeError)
    HTTP2_PING_LENGTH = 98,
    /// TypeError: ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED (instanceof TypeError)
    HTTP2_PSEUDOHEADER_NOT_ALLOWED = 99,
    /// Error: ERR_HTTP2_PUSH_DISABLED (instanceof Error)
    HTTP2_PUSH_DISABLED = 100,
    /// Error: ERR_HTTP2_SEND_FILE_NOSEEK (instanceof Error)
    HTTP2_SEND_FILE_NOSEEK = 101,
    /// Error: ERR_HTTP2_SEND_FILE (instanceof Error)
    HTTP2_SEND_FILE = 102,
    /// Error: ERR_HTTP2_SESSION_ERROR (instanceof Error)
    HTTP2_SESSION_ERROR = 103,
    /// Error: ERR_HTTP2_SOCKET_UNBOUND (instanceof Error)
    HTTP2_SOCKET_UNBOUND = 104,
    /// Error: ERR_HTTP2_STATUS_101 (instanceof Error)
    HTTP2_STATUS_101 = 105,
    /// RangeError: ERR_HTTP2_STATUS_INVALID (instanceof RangeError)
    HTTP2_STATUS_INVALID = 106,
    /// Error: ERR_HTTP2_STREAM_ERROR (instanceof Error)
    HTTP2_STREAM_ERROR = 107,
    /// Error: ERR_HTTP2_TRAILERS_ALREADY_SENT (instanceof Error)
    HTTP2_TRAILERS_ALREADY_SENT = 108,
    /// Error: ERR_HTTP2_TRAILERS_NOT_READY (instanceof Error)
    HTTP2_TRAILERS_NOT_READY = 109,
    /// Error: ERR_HTTP2_TOO_MANY_CUSTOM_SETTINGS (instanceof Error)
    HTTP2_TOO_MANY_CUSTOM_SETTINGS = 110,
    /// Error: ERR_HTTP2_TOO_MANY_INVALID_FRAMES (instanceof Error)
    HTTP2_TOO_MANY_INVALID_FRAMES = 111,
    /// Error: ERR_HTTP2_UNSUPPORTED_PROTOCOL (instanceof Error)
    HTTP2_UNSUPPORTED_PROTOCOL = 112,
    /// TypeError: ERR_HTTP2_INVALID_SETTING_VALUE (instanceof TypeError)
    HTTP2_INVALID_SETTING_VALUE = 113,
    /// TypeError: ERR_HTTP2_INVALID_SETTING_VALUE (instanceof RangeError)
    HTTP2_INVALID_SETTING_VALUE_RangeError = 114,
    /// TypeError: ERR_ILLEGAL_CONSTRUCTOR (instanceof TypeError)
    ILLEGAL_CONSTRUCTOR = 115,
    /// TypeError: ERR_INCOMPATIBLE_OPTION_PAIR (instanceof TypeError)
    INCOMPATIBLE_OPTION_PAIR = 116,
    /// Error: ERR_INVALID_ADDRESS (instanceof Error)
    INVALID_ADDRESS = 117,
    /// RangeError: ERR_INVALID_ADDRESS_FAMILY (instanceof RangeError)
    INVALID_ADDRESS_FAMILY = 118,
    /// TypeError: ERR_INVALID_ARG_TYPE (instanceof TypeError)
    INVALID_ARG_TYPE = 119,
    /// TypeError: ERR_INVALID_ARG_VALUE (instanceof TypeError)
    INVALID_ARG_VALUE = 120,
    /// RangeError: ERR_INVALID_ASYNC_ID (instanceof RangeError)
    INVALID_ASYNC_ID = 121,
    /// TypeError: ERR_INVALID_CHAR (instanceof TypeError)
    INVALID_CHAR = 122,
    /// TypeError: ERR_INVALID_CURSOR_POS (instanceof TypeError)
    INVALID_CURSOR_POS = 123,
    /// TypeError: ERR_INVALID_FD_TYPE (instanceof TypeError)
    INVALID_FD_TYPE = 124,
    /// TypeError: ERR_INVALID_FILE_URL_HOST (instanceof TypeError)
    INVALID_FILE_URL_HOST = 125,
    /// TypeError: ERR_INVALID_FILE_URL_PATH (instanceof TypeError)
    INVALID_FILE_URL_PATH = 126,
    /// TypeError: ERR_INVALID_HANDLE_TYPE (instanceof TypeError)
    INVALID_HANDLE_TYPE = 127,
    /// TypeError: ERR_INVALID_HTTP_TOKEN (instanceof TypeError)
    INVALID_HTTP_TOKEN = 128,
    /// TypeError: ERR_INVALID_IP_ADDRESS (instanceof TypeError)
    INVALID_IP_ADDRESS = 129,
    /// TypeError: ERR_INVALID_MIME_SYNTAX (instanceof TypeError)
    INVALID_MIME_SYNTAX = 130,
    /// Error: ERR_INVALID_MODULE (instanceof Error)
    INVALID_MODULE = 131,
    /// TypeError: ERR_INVALID_OBJECT_DEFINE_PROPERTY (instanceof TypeError)
    INVALID_OBJECT_DEFINE_PROPERTY = 132,
    /// Error: ERR_INVALID_PACKAGE_CONFIG (instanceof Error)
    INVALID_PACKAGE_CONFIG = 133,
    /// TypeError: ERR_INVALID_PROTOCOL (instanceof TypeError)
    INVALID_PROTOCOL = 134,
    /// TypeError: ERR_INVALID_RETURN_VALUE (instanceof TypeError)
    INVALID_RETURN_VALUE = 135,
    /// Error: ERR_INVALID_STATE (instanceof Error)
    INVALID_STATE = 136,
    /// Error: ERR_INVALID_STATE (instanceof TypeError)
    INVALID_STATE_TypeError = 137,
    /// Error: ERR_INVALID_STATE (instanceof RangeError)
    INVALID_STATE_RangeError = 138,
    /// TypeError: ERR_INVALID_THIS (instanceof TypeError)
    INVALID_THIS = 139,
    /// URIError: ERR_INVALID_URI (instanceof URIError)
    INVALID_URI = 140,
    /// TypeError: ERR_INVALID_URL_SCHEME (instanceof TypeError)
    INVALID_URL_SCHEME = 141,
    /// TypeError: ERR_INVALID_URL (instanceof TypeError)
    INVALID_URL = 142,
    /// Error: ERR_IP_BLOCKED (instanceof Error)
    IP_BLOCKED = 143,
    /// Error: ERR_IPC_CHANNEL_CLOSED (instanceof Error)
    IPC_CHANNEL_CLOSED = 144,
    /// Error: ERR_IPC_DISCONNECTED (instanceof Error)
    IPC_DISCONNECTED = 145,
    /// Error: ERR_IPC_ONE_PIPE (instanceof Error)
    IPC_ONE_PIPE = 146,
    /// Error: ERR_LOAD_SQLITE_EXTENSION (instanceof Error)
    LOAD_SQLITE_EXTENSION = 147,
    /// Error: ERR_MEMORY_ALLOCATION_FAILED (instanceof Error)
    MEMORY_ALLOCATION_FAILED = 148,
    /// Error: ERR_MESSAGE_TARGET_CONTEXT_UNAVAILABLE (instanceof Error)
    MESSAGE_TARGET_CONTEXT_UNAVAILABLE = 149,
    /// Error: ERR_METHOD_NOT_IMPLEMENTED (instanceof Error)
    METHOD_NOT_IMPLEMENTED = 150,
    /// TypeError: ERR_MISSING_ARGS (instanceof TypeError)
    MISSING_ARGS = 151,
    /// TypeError: ERR_MISSING_PASSPHRASE (instanceof TypeError)
    MISSING_PASSPHRASE = 152,
    /// Error: ERR_MISSING_PLATFORM_FOR_WORKER (instanceof Error)
    MISSING_PLATFORM_FOR_WORKER = 153,
    /// Error: ERR_MODULE_NOT_FOUND (instanceof Error)
    ERR_MODULE_NOT_FOUND = 154,
    /// Error: ERR_MULTIPLE_CALLBACK (instanceof Error)
    MULTIPLE_CALLBACK = 155,
    /// Error: ERR_NON_CONTEXT_AWARE_DISABLED (instanceof Error)
    NON_CONTEXT_AWARE_DISABLED = 156,
    /// RangeError: ERR_OUT_OF_RANGE (instanceof RangeError)
    OUT_OF_RANGE = 157,
    /// TypeError: ERR_PARSE_ARGS_INVALID_OPTION_VALUE (instanceof TypeError)
    PARSE_ARGS_INVALID_OPTION_VALUE = 158,
    /// TypeError: ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL (instanceof TypeError)
    PARSE_ARGS_UNEXPECTED_POSITIONAL = 159,
    /// TypeError: ERR_PARSE_ARGS_UNKNOWN_OPTION (instanceof TypeError)
    PARSE_ARGS_UNKNOWN_OPTION = 160,
    /// PostgresError: ERR_POSTGRES_AUTHENTICATION_FAILED_PBKDF2 (instanceof Error)
    POSTGRES_AUTHENTICATION_FAILED_PBKDF2 = 161,
    /// PostgresError: ERR_POSTGRES_CONNECTION_CLOSED (instanceof Error)
    POSTGRES_CONNECTION_CLOSED = 162,
    /// PostgresError: ERR_POSTGRES_CONNECTION_TIMEOUT (instanceof Error)
    POSTGRES_CONNECTION_TIMEOUT = 163,
    /// PostgresError: ERR_POSTGRES_EXPECTED_REQUEST (instanceof Error)
    POSTGRES_EXPECTED_REQUEST = 164,
    /// PostgresError: ERR_POSTGRES_EXPECTED_STATEMENT (instanceof Error)
    POSTGRES_EXPECTED_STATEMENT = 165,
    /// PostgresError: ERR_POSTGRES_IDLE_TIMEOUT (instanceof Error)
    POSTGRES_IDLE_TIMEOUT = 166,
    /// PostgresError: ERR_POSTGRES_INVALID_BACKEND_KEY_DATA (instanceof TypeError)
    POSTGRES_INVALID_BACKEND_KEY_DATA = 167,
    /// PostgresError: ERR_POSTGRES_INVALID_BINARY_DATA (instanceof TypeError)
    POSTGRES_INVALID_BINARY_DATA = 168,
    /// PostgresError: ERR_POSTGRES_INVALID_BYTE_SEQUENCE_FOR_ENCODING (instanceof TypeError)
    POSTGRES_INVALID_BYTE_SEQUENCE_FOR_ENCODING = 169,
    /// PostgresError: ERR_POSTGRES_INVALID_BYTE_SEQUENCE (instanceof TypeError)
    POSTGRES_INVALID_BYTE_SEQUENCE = 170,
    /// PostgresError: ERR_POSTGRES_INVALID_CHARACTER (instanceof TypeError)
    POSTGRES_INVALID_CHARACTER = 171,
    /// PostgresError: ERR_POSTGRES_INVALID_MESSAGE_LENGTH (instanceof Error)
    POSTGRES_INVALID_MESSAGE_LENGTH = 172,
    /// PostgresError: ERR_POSTGRES_INVALID_MESSAGE (instanceof Error)
    POSTGRES_INVALID_MESSAGE = 173,
    /// PostgresError: ERR_POSTGRES_INVALID_QUERY_BINDING (instanceof Error)
    POSTGRES_INVALID_QUERY_BINDING = 174,
    /// PostgresError: ERR_POSTGRES_INVALID_SERVER_KEY (instanceof Error)
    POSTGRES_INVALID_SERVER_KEY = 175,
    /// PostgresError: ERR_POSTGRES_INVALID_SERVER_SIGNATURE (instanceof Error)
    POSTGRES_INVALID_SERVER_SIGNATURE = 176,
    /// PostgresError: ERR_POSTGRES_INVALID_TRANSACTION_STATE (instanceof Error)
    POSTGRES_INVALID_TRANSACTION_STATE = 177,
    /// PostgresError: ERR_POSTGRES_LIFETIME_TIMEOUT (instanceof Error)
    POSTGRES_LIFETIME_TIMEOUT = 178,
    /// PostgresError: ERR_POSTGRES_MULTIDIMENSIONAL_ARRAY_NOT_SUPPORTED_YET (instanceof Error)
    POSTGRES_MULTIDIMENSIONAL_ARRAY_NOT_SUPPORTED_YET = 179,
    /// PostgresError: ERR_POSTGRES_NOT_TAGGED_CALL (instanceof Error)
    POSTGRES_NOT_TAGGED_CALL = 180,
    /// PostgresError: ERR_POSTGRES_NULLS_IN_ARRAY_NOT_SUPPORTED_YET (instanceof Error)
    POSTGRES_NULLS_IN_ARRAY_NOT_SUPPORTED_YET = 181,
    /// PostgresError: ERR_POSTGRES_OVERFLOW (instanceof TypeError)
    POSTGRES_OVERFLOW = 182,
    /// PostgresError: ERR_POSTGRES_QUERY_CANCELLED (instanceof Error)
    POSTGRES_QUERY_CANCELLED = 183,
    /// PostgresError: ERR_POSTGRES_SASL_SIGNATURE_INVALID_BASE64 (instanceof Error)
    POSTGRES_SASL_SIGNATURE_INVALID_BASE64 = 184,
    /// PostgresError: ERR_POSTGRES_SASL_SIGNATURE_MISMATCH (instanceof Error)
    POSTGRES_SASL_SIGNATURE_MISMATCH = 185,
    /// PostgresError: ERR_POSTGRES_SERVER_ERROR (instanceof Error)
    POSTGRES_SERVER_ERROR = 186,
    /// PostgresError: ERR_POSTGRES_SYNTAX_ERROR (instanceof SyntaxError)
    POSTGRES_SYNTAX_ERROR = 187,
    /// PostgresError: ERR_POSTGRES_TLS_NOT_AVAILABLE (instanceof Error)
    POSTGRES_TLS_NOT_AVAILABLE = 188,
    /// PostgresError: ERR_POSTGRES_TLS_UPGRADE_FAILED (instanceof Error)
    POSTGRES_TLS_UPGRADE_FAILED = 189,
    /// PostgresError: ERR_POSTGRES_UNEXPECTED_MESSAGE (instanceof Error)
    POSTGRES_UNEXPECTED_MESSAGE = 190,
    /// PostgresError: ERR_POSTGRES_UNKNOWN_AUTHENTICATION_METHOD (instanceof Error)
    POSTGRES_UNKNOWN_AUTHENTICATION_METHOD = 191,
    /// PostgresError: ERR_POSTGRES_UNKNOWN_FORMAT_CODE (instanceof Error)
    POSTGRES_UNKNOWN_FORMAT_CODE = 192,
    /// PostgresError: ERR_POSTGRES_UNSAFE_TRANSACTION (instanceof Error)
    POSTGRES_UNSAFE_TRANSACTION = 193,
    /// PostgresError: ERR_POSTGRES_UNSUPPORTED_ARRAY_FORMAT (instanceof TypeError)
    POSTGRES_UNSUPPORTED_ARRAY_FORMAT = 194,
    /// PostgresError: ERR_POSTGRES_UNSUPPORTED_AUTHENTICATION_METHOD (instanceof Error)
    POSTGRES_UNSUPPORTED_AUTHENTICATION_METHOD = 195,
    /// PostgresError: ERR_POSTGRES_UNSUPPORTED_BYTEA_FORMAT (instanceof TypeError)
    POSTGRES_UNSUPPORTED_BYTEA_FORMAT = 196,
    /// PostgresError: ERR_POSTGRES_UNSUPPORTED_INTEGER_SIZE (instanceof TypeError)
    POSTGRES_UNSUPPORTED_INTEGER_SIZE = 197,
    /// PostgresError: ERR_POSTGRES_UNSUPPORTED_NUMERIC_FORMAT (instanceof TypeError)
    POSTGRES_UNSUPPORTED_NUMERIC_FORMAT = 198,
    /// Error: ERR_PROXY_INVALID_CONFIG (instanceof Error)
    PROXY_INVALID_CONFIG = 199,
    /// MySQLError: ERR_MYSQL_CONNECTION_CLOSED (instanceof Error)
    MYSQL_CONNECTION_CLOSED = 200,
    /// MySQLError: ERR_MYSQL_CONNECTION_TIMEOUT (instanceof Error)
    MYSQL_CONNECTION_TIMEOUT = 201,
    /// MySQLError: ERR_MYSQL_IDLE_TIMEOUT (instanceof Error)
    MYSQL_IDLE_TIMEOUT = 202,
    /// MySQLError: ERR_MYSQL_LIFETIME_TIMEOUT (instanceof Error)
    MYSQL_LIFETIME_TIMEOUT = 203,
    /// UnhandledPromiseRejection: ERR_UNHANDLED_REJECTION (instanceof Error)
    UNHANDLED_REJECTION = 204,
    /// Error: ERR_REQUIRE_ASYNC_MODULE (instanceof Error)
    REQUIRE_ASYNC_MODULE = 205,
    /// Error: ERR_S3_INVALID_ENDPOINT (instanceof Error)
    S3_INVALID_ENDPOINT = 206,
    /// Error: ERR_S3_INVALID_METHOD (instanceof Error)
    S3_INVALID_METHOD = 207,
    /// Error: ERR_S3_INVALID_PATH (instanceof Error)
    S3_INVALID_PATH = 208,
    /// Error: ERR_S3_INVALID_SESSION_TOKEN (instanceof Error)
    S3_INVALID_SESSION_TOKEN = 209,
    /// Error: ERR_S3_INVALID_SIGNATURE (instanceof Error)
    S3_INVALID_SIGNATURE = 210,
    /// Error: ERR_S3_MISSING_CREDENTIALS (instanceof Error)
    S3_MISSING_CREDENTIALS = 211,
    /// Error: ERR_SCRIPT_EXECUTION_INTERRUPTED (instanceof Error)
    SCRIPT_EXECUTION_INTERRUPTED = 212,
    /// Error: ERR_SCRIPT_EXECUTION_TIMEOUT (instanceof Error)
    SCRIPT_EXECUTION_TIMEOUT = 213,
    /// Error: ERR_SERVER_ALREADY_LISTEN (instanceof Error)
    SERVER_ALREADY_LISTEN = 214,
    /// Error: ERR_SERVER_NOT_RUNNING (instanceof Error)
    SERVER_NOT_RUNNING = 215,
    /// Error: ERR_SOCKET_ALREADY_BOUND (instanceof Error)
    SOCKET_ALREADY_BOUND = 216,
    /// TypeError: ERR_SOCKET_BAD_BUFFER_SIZE (instanceof TypeError)
    SOCKET_BAD_BUFFER_SIZE = 217,
    /// RangeError: ERR_SOCKET_BAD_PORT (instanceof RangeError)
    SOCKET_BAD_PORT = 218,
    /// TypeError: ERR_SOCKET_BAD_TYPE (instanceof TypeError)
    SOCKET_BAD_TYPE = 219,
    /// Error: ERR_SOCKET_CLOSED_BEFORE_CONNECTION (instanceof Error)
    SOCKET_CLOSED_BEFORE_CONNECTION = 220,
    /// Error: ERR_SOCKET_CLOSED (instanceof Error)
    SOCKET_CLOSED = 221,
    /// Error: ERR_SOCKET_CONNECTION_TIMEOUT (instanceof Error)
    SOCKET_CONNECTION_TIMEOUT = 222,
    /// Error: ERR_SOCKET_DGRAM_IS_CONNECTED (instanceof Error)
    SOCKET_DGRAM_IS_CONNECTED = 223,
    /// Error: ERR_SOCKET_DGRAM_NOT_CONNECTED (instanceof Error)
    SOCKET_DGRAM_NOT_CONNECTED = 224,
    /// Error: ERR_SOCKET_DGRAM_NOT_RUNNING (instanceof Error)
    SOCKET_DGRAM_NOT_RUNNING = 225,
    /// Error: ERR_SSR_RESPONSE_EXPECTED (instanceof Error)
    SSR_RESPONSE_EXPECTED = 226,
    /// Error: ERR_STREAM_ALREADY_FINISHED (instanceof Error)
    STREAM_ALREADY_FINISHED = 227,
    /// Error: ERR_STREAM_CANNOT_PIPE (instanceof Error)
    STREAM_CANNOT_PIPE = 228,
    /// Error: ERR_STREAM_DESTROYED (instanceof Error)
    STREAM_DESTROYED = 229,
    /// TypeError: ERR_STREAM_NULL_VALUES (instanceof TypeError)
    STREAM_NULL_VALUES = 230,
    /// Error: ERR_STREAM_PREMATURE_CLOSE (instanceof Error)
    STREAM_PREMATURE_CLOSE = 231,
    /// Error: ERR_STREAM_PUSH_AFTER_EOF (instanceof Error)
    STREAM_PUSH_AFTER_EOF = 232,
    /// AbortError: ERR_STREAM_RELEASE_LOCK (instanceof Error)
    STREAM_RELEASE_LOCK = 233,
    /// Error: ERR_STREAM_UNABLE_TO_PIPE (instanceof Error)
    STREAM_UNABLE_TO_PIPE = 234,
    /// Error: ERR_STREAM_UNSHIFT_AFTER_END_EVENT (instanceof Error)
    STREAM_UNSHIFT_AFTER_END_EVENT = 235,
    /// Error: ERR_STREAM_WRAP (instanceof Error)
    STREAM_WRAP = 236,
    /// Error: ERR_STREAM_WRITE_AFTER_END (instanceof Error)
    STREAM_WRITE_AFTER_END = 237,
    /// Error: ERR_STRING_TOO_LONG (instanceof Error)
    STRING_TOO_LONG = 238,
    /// SyntaxError: ERR_TLS_CERT_ALTNAME_FORMAT (instanceof SyntaxError)
    TLS_CERT_ALTNAME_FORMAT = 239,
    /// Error: ERR_TLS_CERT_ALTNAME_INVALID (instanceof Error)
    TLS_CERT_ALTNAME_INVALID = 240,
    /// Error: ERR_TLS_HANDSHAKE_TIMEOUT (instanceof Error)
    TLS_HANDSHAKE_TIMEOUT = 241,
    /// TypeError: ERR_TLS_INVALID_PROTOCOL_METHOD (instanceof TypeError)
    TLS_INVALID_PROTOCOL_METHOD = 242,
    /// TypeError: ERR_TLS_INVALID_PROTOCOL_VERSION (instanceof TypeError)
    TLS_INVALID_PROTOCOL_VERSION = 243,
    /// TypeError: ERR_TLS_PROTOCOL_VERSION_CONFLICT (instanceof TypeError)
    TLS_PROTOCOL_VERSION_CONFLICT = 244,
    /// Error: ERR_TLS_PSK_SET_IDENTITY_HINT_FAILED (instanceof Error)
    TLS_PSK_SET_IDENTITY_HINT_FAILED = 245,
    /// Error: ERR_TLS_RENEGOTIATION_DISABLED (instanceof Error)
    TLS_RENEGOTIATION_DISABLED = 246,
    /// Error: ERR_TLS_SNI_FROM_SERVER (instanceof Error)
    TLS_SNI_FROM_SERVER = 247,
    /// TypeError: ERR_TLS_ALPN_CALLBACK_WITH_PROTOCOLS (instanceof TypeError)
    TLS_ALPN_CALLBACK_WITH_PROTOCOLS = 248,
    /// Error: ERR_SSL_NO_CIPHER_MATCH (instanceof Error)
    SSL_NO_CIPHER_MATCH = 249,
    /// Error: ERR_UNAVAILABLE_DURING_EXIT (instanceof Error)
    UNAVAILABLE_DURING_EXIT = 250,
    /// Error: ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET (instanceof Error)
    UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET = 251,
    /// TypeError: ERR_UNESCAPED_CHARACTERS (instanceof TypeError)
    UNESCAPED_CHARACTERS = 252,
    /// Error: ERR_UNHANDLED_ERROR (instanceof Error)
    UNHANDLED_ERROR = 253,
    /// Error: ERR_UNKNOWN_CREDENTIAL (instanceof Error)
    UNKNOWN_CREDENTIAL = 254,
    /// TypeError: ERR_UNKNOWN_ENCODING (instanceof TypeError)
    UNKNOWN_ENCODING = 255,
    /// TypeError: ERR_UNKNOWN_SIGNAL (instanceof TypeError)
    UNKNOWN_SIGNAL = 256,
    /// RangeError: ERR_ZSTD_INVALID_PARAM (instanceof RangeError)
    ZSTD_INVALID_PARAM = 257,
    /// Error: ERR_USE_AFTER_CLOSE (instanceof Error)
    USE_AFTER_CLOSE = 258,
    /// Error: ERR_WASI_NOT_STARTED (instanceof Error)
    WASI_NOT_STARTED = 259,
    /// TypeError: ERR_WEBASSEMBLY_RESPONSE (instanceof TypeError)
    WEBASSEMBLY_RESPONSE = 260,
    /// Error: ERR_WORKER_INIT_FAILED (instanceof Error)
    WORKER_INIT_FAILED = 261,
    /// Error: ERR_WORKER_NOT_RUNNING (instanceof Error)
    WORKER_NOT_RUNNING = 262,
    /// TypeError: ERR_WORKER_UNSUPPORTED_OPERATION (instanceof TypeError)
    WORKER_UNSUPPORTED_OPERATION = 263,
    /// Error: ERR_ZLIB_INITIALIZATION_FAILED (instanceof Error)
    ZLIB_INITIALIZATION_FAILED = 264,
    /// Error: MODULE_NOT_FOUND (instanceof Error)
    MODULE_NOT_FOUND = 265,
    /// Error: ERR_INTERNAL_ASSERTION (instanceof Error)
    INTERNAL_ASSERTION = 266,
    /// Error: ERR_OSSL_EVP_INVALID_DIGEST (instanceof Error)
    OSSL_EVP_INVALID_DIGEST = 267,
    /// Error: ERR_KEY_GENERATION_JOB_FAILED (instanceof Error)
    KEY_GENERATION_JOB_FAILED = 268,
    /// TypeError: ERR_MISSING_OPTION (instanceof TypeError)
    MISSING_OPTION = 269,
    /// RedisError: ERR_REDIS_AUTHENTICATION_FAILED (instanceof Error)
    REDIS_AUTHENTICATION_FAILED = 270,
    /// RedisError: ERR_REDIS_CONNECTION_CLOSED (instanceof Error)
    REDIS_CONNECTION_CLOSED = 271,
    /// RedisError: ERR_REDIS_CONNECTION_TIMEOUT (instanceof Error)
    REDIS_CONNECTION_TIMEOUT = 272,
    /// RedisError: ERR_REDIS_IDLE_TIMEOUT (instanceof Error)
    REDIS_IDLE_TIMEOUT = 273,
    /// RedisError: ERR_REDIS_INVALID_ARGUMENT (instanceof Error)
    REDIS_INVALID_ARGUMENT = 274,
    /// RedisError: ERR_REDIS_INVALID_ARRAY (instanceof Error)
    REDIS_INVALID_ARRAY = 275,
    /// RedisError: ERR_REDIS_INVALID_BULK_STRING (instanceof Error)
    REDIS_INVALID_BULK_STRING = 276,
    /// RedisError: ERR_REDIS_INVALID_COMMAND (instanceof Error)
    REDIS_INVALID_COMMAND = 277,
    /// RedisError: ERR_REDIS_INVALID_DATABASE (instanceof Error)
    REDIS_INVALID_DATABASE = 278,
    /// RedisError: ERR_REDIS_INVALID_ERROR_STRING (instanceof Error)
    REDIS_INVALID_ERROR_STRING = 279,
    /// RedisError: ERR_REDIS_INVALID_INTEGER (instanceof Error)
    REDIS_INVALID_INTEGER = 280,
    /// RedisError: ERR_REDIS_INVALID_PASSWORD (instanceof Error)
    REDIS_INVALID_PASSWORD = 281,
    /// RedisError: ERR_REDIS_INVALID_RESPONSE (instanceof Error)
    REDIS_INVALID_RESPONSE = 282,
    /// RedisError: ERR_REDIS_INVALID_RESPONSE_TYPE (instanceof Error)
    REDIS_INVALID_RESPONSE_TYPE = 283,
    /// RedisError: ERR_REDIS_INVALID_SIMPLE_STRING (instanceof Error)
    REDIS_INVALID_SIMPLE_STRING = 284,
    /// RedisError: ERR_REDIS_INVALID_STATE (instanceof Error)
    REDIS_INVALID_STATE = 285,
    /// RedisError: ERR_REDIS_INVALID_USERNAME (instanceof Error)
    REDIS_INVALID_USERNAME = 286,
    /// RedisError: ERR_REDIS_TLS_NOT_AVAILABLE (instanceof Error)
    REDIS_TLS_NOT_AVAILABLE = 287,
    /// RedisError: ERR_REDIS_TLS_UPGRADE_FAILED (instanceof Error)
    REDIS_TLS_UPGRADE_FAILED = 288,
    /// Error: HPE_UNEXPECTED_CONTENT_LENGTH (instanceof Error)
    HPE_UNEXPECTED_CONTENT_LENGTH = 289,
    /// Error: HPE_INVALID_TRANSFER_ENCODING (instanceof Error)
    HPE_INVALID_TRANSFER_ENCODING = 290,
    /// Error: HPE_INVALID_EOF_STATE (instanceof Error)
    HPE_INVALID_EOF_STATE = 291,
    /// Error: HPE_INVALID_METHOD (instanceof Error)
    HPE_INVALID_METHOD = 292,
    /// Error: HPE_INTERNAL (instanceof Error)
    HPE_INTERNAL = 293,
    /// Error: ERR_VM_MODULE_STATUS (instanceof Error)
    VM_MODULE_STATUS = 294,
    /// Error: ERR_VM_MODULE_ALREADY_LINKED (instanceof Error)
    VM_MODULE_ALREADY_LINKED = 295,
    /// Error: ERR_VM_MODULE_CANNOT_CREATE_CACHED_DATA (instanceof Error)
    VM_MODULE_CANNOT_CREATE_CACHED_DATA = 296,
    /// Error: ERR_VM_MODULE_NOT_MODULE (instanceof Error)
    VM_MODULE_NOT_MODULE = 297,
    /// Error: ERR_VM_MODULE_DIFFERENT_CONTEXT (instanceof Error)
    VM_MODULE_DIFFERENT_CONTEXT = 298,
    /// Error: ERR_VM_MODULE_LINK_FAILURE (instanceof Error)
    VM_MODULE_LINK_FAILURE = 299,
    /// Error: ERR_VM_MODULE_CACHED_DATA_REJECTED (instanceof Error)
    VM_MODULE_CACHED_DATA_REJECTED = 300,
    /// TypeError: ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING (instanceof TypeError)
    VM_DYNAMIC_IMPORT_CALLBACK_MISSING = 301,
    /// Error: HPE_INVALID_HEADER_TOKEN (instanceof Error)
    HPE_INVALID_HEADER_TOKEN = 302,
    /// Error: HPE_HEADER_OVERFLOW (instanceof Error)
    HPE_HEADER_OVERFLOW = 303,
    /// Error: ERR_SECRETS_NOT_AVAILABLE (instanceof Error)
    SECRETS_NOT_AVAILABLE = 304,
    /// Error: ERR_SECRETS_NOT_FOUND (instanceof Error)
    SECRETS_NOT_FOUND = 305,
    /// Error: ERR_SECRETS_ACCESS_DENIED (instanceof Error)
    SECRETS_ACCESS_DENIED = 306,
    /// Error: ERR_SECRETS_PLATFORM_ERROR (instanceof Error)
    SECRETS_PLATFORM_ERROR = 307,
    /// Error: ERR_SECRETS_USER_CANCELED (instanceof Error)
    SECRETS_USER_CANCELED = 308,
    /// Error: ERR_SECRETS_INTERACTION_NOT_ALLOWED (instanceof Error)
    SECRETS_INTERACTION_NOT_ALLOWED = 309,
    /// Error: ERR_SECRETS_AUTH_FAILED (instanceof Error)
    SECRETS_AUTH_FAILED = 310,
    /// Error: ERR_SECRETS_INTERACTION_REQUIRED (instanceof Error)
    SECRETS_INTERACTION_REQUIRED = 311,



  extern fn Bun__createErrorWithCode(globalThis: *jsc.JSGlobalObject, code: Error, message: *bun.String) jsc.JSValue;

  /// Creates an Error object with the given error code.
  /// If an error is thrown while creating the Error object, returns that error instead.
  /// Derefs the message string.
  pub fn toJS(this: Error, globalThis: *jsc.JSGlobalObject, message: *bun.String) jsc.JSValue {
    defer message.deref();
    return Bun__createErrorWithCode(globalThis, this, message);
  }

  pub fn fmt(this: Error, globalThis: *jsc.JSGlobalObject, comptime fmt_str: [:0]const u8, args: anytype) jsc.JSValue {
    if (comptime std.meta.fieldNames(@TypeOf(args)).len == 0) {
      var message = bun.String.static(fmt_str);
      return toJS(this, globalThis, &message);
    }

    var message = bun.handleOom(bun.String.createFormat(fmt_str, args));
    return toJS(this, globalThis, &message);
  }

  pub fn throw(this: Error, globalThis: *jsc.JSGlobalObject, comptime fmt_str: [:0]const u8, args: anytype) bun.JSError {
    return globalThis.throwValue(fmt(this, globalThis, fmt_str, args));
  }

};
