[package]
name = "ion-stdlib"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Standard Library - Built-in modules and functions"
license = "MIT"

[dependencies]
ion-ast = { path = "../ast" }
ion-types = { path = "../types" }

[scripts]
test = "zig test src/stdlib.zig"
