// Copied verbatim from bun/src/perf/generated_perf_trace_events.zig at
// upstream SHA fd0b6f1a271fca0b8124b69f230b100f4d636af6. MIT — see
// ../cli/LICENSE.bun.md.
//
// This file is upstream-generated by `scripts/generate-perf-trace-events.sh`.
// The Home runtime re-uses Bun's event tag set verbatim; when Phase
// 12.5 starts emitting Home-specific events the generator is re-run
// here.

// Generated with scripts/generate-perf-trace-events.sh
pub const PerfEvent = enum(i32) {
    @"Bundler.BindImportsToExports",
    @"Bundler.breakOutputIntoPieces",
    @"Bundler.cloneAST",
    @"Bundler.CloneLinkerGraph",
    @"Bundler.computeChunks",
    @"Bundler.CreateNamespaceExports",
    @"Bundler.FigureOutCommonJS",
    @"Bundler.findAllImportedPartsInJSOrder",
    @"Bundler.findReachableFiles",
    @"Bundler.generateChunksInParallel",
    @"Bundler.generateCodeForFileInChunkCss",
    @"Bundler.generateCodeForFileInChunkJS",
    @"Bundler.generateIsolatedHash",
    @"Bundler.generateSourceMapForChunk",
    @"Bundler.markFileLiveForTreeShaking",
    @"Bundler.markFileReachableForCodeSplitting",
    @"Bundler.MatchImportsWithExports",
    @"Bundler.onParseTaskComplete",
    @"Bundler.ParseJS",
    @"Bundler.ParseJSON",
    @"Bundler.ParseJSON5",
    @"Bundler.ParseTOML",
    @"Bundler.ParseYAML",
    @"Bundler.postProcessJSChunk",
    @"Bundler.readFile",
    @"Bundler.renameSymbolsInChunk",
    @"Bundler.ResolveExportStarStatements",
    @"Bundler.scanImportsAndExports",
    @"Bundler.treeShakingAndCodeSplitting",
    @"Bundler.Worker.create",
    @"Bundler.WrapDependencies",
    @"Bundler.writeChunkToDisk",
    @"Bundler.writeOutputFilesToDisk",
    @"ExtractTarball.extract",
    @"FolderResolver.readPackageJSONFromDisk.folder",
    @"FolderResolver.readPackageJSONFromDisk.workspace",
    @"JSBundler.addPlugin",
    @"JSBundler.hasAnyMatches",
    @"JSBundler.matchOnLoad",
    @"JSBundler.matchOnResolve",
    @"JSGlobalObject.create",
    @"JSParser.analyze",
    @"JSParser.parse",
    @"JSParser.postvisit",
    @"JSParser.visit",
    @"JSPrinter.print",
    @"JSPrinter.printWithSourceMap",
    @"ModuleResolver.resolve",
    @"PackageInstaller.install",
    @"PackageManifest.Serializer.loadByFile",
    @"PackageManifest.Serializer.save",
    @"RuntimeTranspilerCache.fromFile",
    @"RuntimeTranspilerCache.save",
    @"RuntimeTranspilerCache.toFile",
    @"StandaloneModuleGraph.serialize",
    @"Symbols.followAll",
    @"TestCommand.printCodeCoverageLCov",
    @"TestCommand.printCodeCoverageLCovAndText",
    @"TestCommand.printCodeCoverageText",
};

test "generated_perf_trace_events: PerfEvent is a tagged i32 enum" {
    const std = @import("std");
    try std.testing.expectEqual(@as(i32, 0), @intFromEnum(PerfEvent.@"Bundler.BindImportsToExports"));
    // The enum has @"JSParser.parse" — round-trip through @tagName proves
    // the literal is present.
    try std.testing.expectEqualStrings("JSParser.parse", @tagName(PerfEvent.@"JSParser.parse"));
    // Last tag in the upstream list is `TestCommand.printCodeCoverageText`.
    try std.testing.expectEqualStrings(
        "TestCommand.printCodeCoverageText",
        @tagName(PerfEvent.@"TestCommand.printCodeCoverageText"),
    );
}
