[package]
name = "ion-diagnostics"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Diagnostics - Error reporting and source location tracking"
license = "MIT"

[dependencies]
# Standalone diagnostics

[scripts]
test = "zig test src/diagnostics.zig"
