[package]
name = "ion-codegen"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Code Generator - Native machine code generation"
license = "MIT"

[dependencies]
ion-ast = { path = "../ast" }

[scripts]
test = "zig test src/native_codegen.zig"
