import assert from 'node:assert/strict'
import { PerformanceObserver, PerformanceObserverEntryList, PerformanceResourceTiming, performance as nodePerformance } from 'node:perf_hooks'

assert.equal(globalThis.PerformanceObserver, PerformanceObserver)
assert.equal(globalThis.PerformanceObserverEntryList, PerformanceObserverEntryList)
assert.equal(globalThis.PerformanceResourceTiming, PerformanceResourceTiming)
performance.clearResourceTimings()
performance.setResourceTimingBufferSize(250)
const make = (start, name) => performance.markResourceTiming({ startTime: start, endTime: start + 4, encodedBodySize: 12, decodedBodySize: 12 }, name, 'fetch', globalThis, '', undefined, 200)
const first = make(1, 'first')
const second = nodePerformance.markResourceTiming({ startTime: 2, endTime: 8, encodedBodySize: 16, decodedBodySize: 16 }, 'second', 'fetch', globalThis, '', undefined, 200)
assert(first instanceof globalThis.PerformanceResourceTiming)
assert.deepEqual(performance.getEntriesByType('resource'), [first, second])
assert.deepEqual(nodePerformance.getEntriesByType('resource'), [first, second])
assert.equal(performance.getEntriesByName('first', 'resource')[0], first)
assert.equal(nodePerformance.getEntriesByName('second', 'resource')[0], second)
assert.equal(nodePerformance.getEntries().filter(entry => entry.entryType === 'resource').length, 2)
let entries
const observer = new globalThis.PerformanceObserver(list => {
  assert(list instanceof globalThis.PerformanceObserverEntryList)
  entries = list.getEntries()
})
observer.observe({ type: 'resource', buffered: true })
await new Promise(resolve => setImmediate(resolve))
await new Promise(resolve => setImmediate(resolve))
assert.deepEqual(entries, [first, second])
observer.disconnect()
nodePerformance.clearResourceTimings('first')
assert.deepEqual(performance.getEntriesByType('resource'), [second])
assert.deepEqual(nodePerformance.getEntriesByType('resource'), [second])
performance.clearResourceTimings()
assert.deepEqual(nodePerformance.getEntriesByType('resource'), [])
performance.setResourceTimingBufferSize(1)
make(3, 'capacity-first')
make(4, 'capacity-second')
assert.equal(nodePerformance.getEntriesByType('resource').length, 1)
await new Promise(resolve => setImmediate(resolve))
nodePerformance.clearResourceTimings()
nodePerformance.setResourceTimingBufferSize(250)
assert.throws(() => performance.markResourceTiming(), { code: 'ERR_INTERNAL_ASSERTION' })
console.log('native global/Node resource identity, shared constructors, queries, observer buffer and selective clearing passed')
