const std = @import("std");

/// LLVM-backed launcher generation for JavaScript and TypeScript entrypoints.
///
/// JavaScript remains a dynamic language executed by Home's JavaScriptCore
/// runtime. The native launcher produced from this IR embeds that runtime and
/// the entry source, extracts both into private temporary files, and executes
/// `home run` with the native VM forced on. This keeps JS/TS semantics in the
/// runtime while LLVM owns the platform executable entrypoint.
pub fn isSupportedEntrypoint(path: []const u8) bool {
    const extension = std.fs.path.extension(path);
    const extensions = [_][]const u8{ ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".mts", ".cts" };
    for (extensions) |candidate| {
        if (std.mem.eql(u8, extension, candidate)) return true;
    }
    return false;
}

pub fn entrypointSuffix(path: []const u8) ![]const u8 {
    if (!isSupportedEntrypoint(path)) return error.UnsupportedJSEntrypoint;
    return std.fs.path.extension(path);
}

pub fn defaultOutputPath(allocator: std.mem.Allocator, path: []const u8) ![]u8 {
    const suffix = try entrypointSuffix(path);
    return allocator.dupe(u8, path[0 .. path.len - suffix.len]);
}

/// Emit the host-side LLVM IR launcher. The host Clang driver compiles this
/// module to a native object; the build pipeline links it with the payload
/// object generated by `generatePayloadAssembly`.
pub fn generateLauncherIR(allocator: std.mem.Allocator, entry_path: []const u8) ![]u8 {
    const suffix = try entrypointSuffix(entry_path);
    const template_prefix = "/tmp/home-entry-XXXXXX";
    const template_len = template_prefix.len + suffix.len + 1;

    var output = std.ArrayList(u8).empty;
    errdefer output.deinit(allocator);

    try output.print(
        allocator,
        "@entry_template = private global [{d} x i8] c\"{s}{s}\\00\"\n",
        .{ template_len, template_prefix, suffix },
    );
    try output.appendSlice(allocator,
        \\@runtime_template = private global [25 x i8] c"/tmp/home-runtime-XXXXXX\00"
        \\@run_arg = private constant [4 x i8] c"run\00"
        \\@native_vm_name = private constant [15 x i8] c"HOME_NATIVE_VM\00"
        \\@native_vm_value = private constant [2 x i8] c"1\00"
        \\@error_message = private constant [25 x i8] c"home compiled entrypoint\00"
        \\
        \\@home_runtime_start = external constant i8
        \\@home_runtime_end = external constant i8
        \\@home_source_start = external constant i8
        \\@home_source_end = external constant i8
        \\
        \\declare i32 @mkstemp(ptr)
        \\declare i32 @mkstemps(ptr, i32)
        \\declare i64 @write(i32, ptr, i64)
        \\declare i32 @fchmod(i32, i32)
        \\declare i32 @close(i32)
        \\declare i32 @unlink(ptr)
        \\declare i32 @fork()
        \\declare i32 @waitpid(i32, ptr, i32)
        \\declare i32 @setenv(ptr, ptr, i32)
        \\declare i32 @execv(ptr, ptr)
        \\declare void @perror(ptr)
        \\declare void @_exit(i32) noreturn
        \\
        \\define internal i32 @write_all(i32 %fd, ptr %data, i64 %length) {
        \\entry:
        \\  br label %loop
        \\
        \\loop:
        \\  %offset = phi i64 [ 0, %entry ], [ %next_offset, %wrote ]
        \\  %done = icmp eq i64 %offset, %length
        \\  br i1 %done, label %success, label %write_chunk
        \\
        \\write_chunk:
        \\  %chunk = getelementptr i8, ptr %data, i64 %offset
        \\  %remaining = sub i64 %length, %offset
        \\  %written = call i64 @write(i32 %fd, ptr %chunk, i64 %remaining)
        \\  %failed = icmp sle i64 %written, 0
        \\  br i1 %failed, label %failure, label %wrote
        \\
        \\wrote:
        \\  %next_offset = add i64 %offset, %written
        \\  br label %loop
        \\
        \\success:
        \\  ret i32 0
        \\
        \\failure:
        \\  ret i32 -1
        \\}
        \\
        \\define i32 @main(i32 %argc, ptr %argv) {
        \\entry:
        \\  %runtime_fd = call i32 @mkstemp(ptr @runtime_template)
        \\  %runtime_open_failed = icmp slt i32 %runtime_fd, 0
        \\  br i1 %runtime_open_failed, label %fail_runtime_open, label %write_runtime
        \\
        \\write_runtime:
        \\  %runtime_start = ptrtoint ptr @home_runtime_start to i64
        \\  %runtime_end = ptrtoint ptr @home_runtime_end to i64
        \\  %runtime_length = sub i64 %runtime_end, %runtime_start
        \\  %runtime_write = call i32 @write_all(i32 %runtime_fd, ptr @home_runtime_start, i64 %runtime_length)
        \\  %runtime_chmod = call i32 @fchmod(i32 %runtime_fd, i32 448)
        \\  %runtime_close = call i32 @close(i32 %runtime_fd)
        \\  %runtime_write_failed = icmp ne i32 %runtime_write, 0
        \\  %runtime_chmod_failed = icmp ne i32 %runtime_chmod, 0
        \\  %runtime_failed = or i1 %runtime_write_failed, %runtime_chmod_failed
        \\  br i1 %runtime_failed, label %fail_runtime, label %open_source
        \\
        \\open_source:
        \\  %source_fd = call i32 @mkstemps(ptr @entry_template, i32
    );
    try output.print(allocator, " {d}", .{suffix.len});
    try output.appendSlice(allocator,
        \\)
        \\  %source_open_failed = icmp slt i32 %source_fd, 0
        \\  br i1 %source_open_failed, label %fail_runtime, label %write_source
        \\
        \\write_source:
        \\  %source_start = ptrtoint ptr @home_source_start to i64
        \\  %source_end = ptrtoint ptr @home_source_end to i64
        \\  %source_length = sub i64 %source_end, %source_start
        \\  %source_write = call i32 @write_all(i32 %source_fd, ptr @home_source_start, i64 %source_length)
        \\  %source_close = call i32 @close(i32 %source_fd)
        \\  %source_failed = icmp ne i32 %source_write, 0
        \\  br i1 %source_failed, label %fail_both, label %spawn_runtime
        \\
        \\spawn_runtime:
        \\  %child = call i32 @fork()
        \\  %fork_failed = icmp slt i32 %child, 0
        \\  br i1 %fork_failed, label %fail_both, label %dispatch_child
        \\
        \\dispatch_child:
        \\  %is_child = icmp eq i32 %child, 0
        \\  br i1 %is_child, label %child_process, label %parent_process
        \\
        \\child_process:
        \\  %argument_count = add i32 %argc, 3
        \\  %argument_count_64 = zext i32 %argument_count to i64
        \\  %child_argv = alloca ptr, i64 %argument_count_64
        \\  %arg0 = getelementptr ptr, ptr %child_argv, i64 0
        \\  store ptr @runtime_template, ptr %arg0
        \\  %arg1 = getelementptr ptr, ptr %child_argv, i64 1
        \\  store ptr @run_arg, ptr %arg1
        \\  %arg2 = getelementptr ptr, ptr %child_argv, i64 2
        \\  store ptr @entry_template, ptr %arg2
        \\  br label %copy_arguments
        \\
        \\copy_arguments:
        \\  %index = phi i32 [ 1, %child_process ], [ %next_index, %copy_argument ]
        \\  %arguments_done = icmp sge i32 %index, %argc
        \\  br i1 %arguments_done, label %finish_arguments, label %copy_argument
        \\
        \\copy_argument:
        \\  %index_64 = zext i32 %index to i64
        \\  %source_argument_ptr = getelementptr ptr, ptr %argv, i64 %index_64
        \\  %source_argument = load ptr, ptr %source_argument_ptr
        \\  %destination_index = add i64 %index_64, 2
        \\  %destination_argument = getelementptr ptr, ptr %child_argv, i64 %destination_index
        \\  store ptr %source_argument, ptr %destination_argument
        \\  %next_index = add i32 %index, 1
        \\  br label %copy_arguments
        \\
        \\finish_arguments:
        \\  %null_index_32 = add i32 %argc, 2
        \\  %null_index = zext i32 %null_index_32 to i64
        \\  %null_argument = getelementptr ptr, ptr %child_argv, i64 %null_index
        \\  store ptr null, ptr %null_argument
        \\  %set_native_vm = call i32 @setenv(ptr @native_vm_name, ptr @native_vm_value, i32 1)
        \\  %exec_result = call i32 @execv(ptr @runtime_template, ptr %child_argv)
        \\  call void @perror(ptr @error_message)
        \\  call void @_exit(i32 127)
        \\  unreachable
        \\
        \\parent_process:
        \\  %status = alloca i32
        \\  %waited = call i32 @waitpid(i32 %child, ptr %status, i32 0)
        \\  %wait_failed = icmp slt i32 %waited, 0
        \\  br i1 %wait_failed, label %fail_both, label %decode_status
        \\
        \\decode_status:
        \\  %raw_status = load i32, ptr %status
        \\  %signal = and i32 %raw_status, 127
        \\  %exited = icmp eq i32 %signal, 0
        \\  %shifted_status = lshr i32 %raw_status, 8
        \\  %exit_status = and i32 %shifted_status, 255
        \\  %signal_status = add i32 %signal, 128
        \\  %result = select i1 %exited, i32 %exit_status, i32 %signal_status
        \\  %remove_runtime = call i32 @unlink(ptr @runtime_template)
        \\  %remove_source = call i32 @unlink(ptr @entry_template)
        \\  ret i32 %result
        \\
        \\fail_both:
        \\  call void @perror(ptr @error_message)
        \\  %remove_failed_source = call i32 @unlink(ptr @entry_template)
        \\  br label %remove_failed_runtime
        \\
        \\fail_runtime:
        \\  call void @perror(ptr @error_message)
        \\  br label %remove_failed_runtime
        \\
        \\remove_failed_runtime:
        \\  %remove_failed_runtime_result = call i32 @unlink(ptr @runtime_template)
        \\  ret i32 1
        \\
        \\fail_runtime_open:
        \\  call void @perror(ptr @error_message)
        \\  ret i32 1
        \\}
        \\
    );

    return output.toOwnedSlice(allocator);
}

/// Generate a tiny assembly object that gives the LLVM launcher stable
/// symbols for the embedded Home runtime and entry source. `.incbin` avoids
/// expanding a large runtime executable into textual LLVM IR.
pub fn generatePayloadAssembly(
    allocator: std.mem.Allocator,
    runtime_path: []const u8,
    source_path: []const u8,
    os_tag: std.Target.Os.Tag,
) ![]u8 {
    if (os_tag != .macos and os_tag != .linux) return error.UnsupportedHost;

    var output = std.ArrayList(u8).empty;
    errdefer output.deinit(allocator);
    const symbol_prefix: []const u8 = if (os_tag == .macos) "_" else "";

    if (os_tag == .macos) {
        try output.appendSlice(allocator, ".section __HOME,__runtime,regular,no_dead_strip\n");
    } else {
        try output.appendSlice(allocator, ".section .rodata.home_runtime,\"a\",@progbits\n");
    }
    try output.print(allocator, ".globl {s}home_runtime_start\n{s}home_runtime_start:\n.incbin ", .{ symbol_prefix, symbol_prefix });
    try appendAssemblyString(&output, allocator, runtime_path);
    try output.print(allocator, "\n.globl {s}home_runtime_end\n{s}home_runtime_end:\n", .{ symbol_prefix, symbol_prefix });

    if (os_tag == .macos) {
        try output.appendSlice(allocator, ".section __HOME,__source,regular,no_dead_strip\n");
    } else {
        try output.appendSlice(allocator, ".section .rodata.home_source,\"a\",@progbits\n");
    }
    try output.print(allocator, ".globl {s}home_source_start\n{s}home_source_start:\n.incbin ", .{ symbol_prefix, symbol_prefix });
    try appendAssemblyString(&output, allocator, source_path);
    try output.print(allocator, "\n.globl {s}home_source_end\n{s}home_source_end:\n", .{ symbol_prefix, symbol_prefix });

    if (os_tag == .linux) {
        try output.appendSlice(allocator, ".section .note.GNU-stack,\"\",@progbits\n");
    }

    return output.toOwnedSlice(allocator);
}

fn appendAssemblyString(output: *std.ArrayList(u8), allocator: std.mem.Allocator, value: []const u8) !void {
    try output.append(allocator, '"');
    for (value) |character| {
        if (character == '"' or character == '\\') try output.append(allocator, '\\');
        try output.append(allocator, character);
    }
    try output.append(allocator, '"');
}

test "JS LLVM entrypoint recognizes supported source extensions" {
    try std.testing.expect(isSupportedEntrypoint("src/main.ts"));
    try std.testing.expect(isSupportedEntrypoint("src/main.mjs"));
    try std.testing.expect(isSupportedEntrypoint("src/main.cts"));
    try std.testing.expect(!isSupportedEntrypoint("src/main.home"));
    try std.testing.expect(!isSupportedEntrypoint("src/main.json"));
}

test "JS LLVM entrypoint derives output path" {
    const output = try defaultOutputPath(std.testing.allocator, "src/main.tsx");
    defer std.testing.allocator.free(output);
    try std.testing.expectEqualStrings("src/main", output);
}

test "JS LLVM launcher preserves entry suffix and native VM dispatch" {
    const ir = try generateLauncherIR(std.testing.allocator, "app.mts");
    defer std.testing.allocator.free(ir);
    try std.testing.expect(std.mem.indexOf(u8, ir, "/tmp/home-entry-XXXXXX.mts") != null);
    try std.testing.expect(std.mem.indexOf(u8, ir, "HOME_NATIVE_VM") != null);
    try std.testing.expect(std.mem.indexOf(u8, ir, "define i32 @main") != null);
}

test "JS LLVM payload assembly escapes paths" {
    const assembly = try generatePayloadAssembly(
        std.testing.allocator,
        "/tmp/home runtime",
        "/tmp/source\"file.ts",
        .linux,
    );
    defer std.testing.allocator.free(assembly);
    try std.testing.expect(std.mem.indexOf(u8, assembly, ".incbin \"/tmp/home runtime\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, assembly, ".incbin \"/tmp/source\\\"file.ts\"") != null);
}
