// Copied from bun/src/runtime/cli/ci_info.zig at upstream SHA
// fd0b6f1a271fca0b8124b69f230b100f4d636af6. MIT — see ../../cli/LICENSE.bun.md.
//
// Rewrites:
//   - @import("bun")                  → @import("home_rt")
//   - bun.env_var.CI.get()            → home_rt.env_var.CI.get()
//     (upstream returns bool-or-null and was treated as a fall-through
//     gate; Home's `env_var.CI` returns `?bool` already, so the gate
//     becomes `CI.get() orelse false`.)
//   - `bun.once(...)` memoization is parked: home_rt does not yet expose
//     the `Once` helper, so the wrappers call into the uncached body
//     each time. The detector is a handful of env_var lookups and
//     small string compares — the cost is negligible at CLI startup.
//   - `@import("ci_info")` (TypeScript-generated by
//     src/codegen/ci_info.ts) is NOT YET PORTED. Until the codegen runs
//     in Home, `detectCIName()` returns `null` and `isCI()` reports the
//     plain `CI=` env-var truth value. The public API shape matches
//     upstream so the future codegen drops in without API churn.
// No Bun→Home identifier renames apply.
//
// A modified port of ci-info@4.0.0 (https://github.com/watson/ci-info)
// Only gets the CI name, `isPR` is not implemented.
// Main implementation is in src/codegen/ci_info.ts (parked).

/// returns true if the current process is running in a CI environment
pub fn isCI() bool {
    return isCIUncached();
}

/// returns the CI name, or null if the CI name could not be determined. note that this can be null even if `isCI` is true.
pub fn detectCIName() ?[]const u8 {
    return detectUncached();
}

fn isCIUncached() bool {
    if (home_rt.env_var.CI.get()) |v| return v or detectCIName() != null;
    return generated.isCIUncachedGenerated() or detectCIName() != null;
}
fn detectUncached() ?[]const u8 {
    // Upstream early-exits when `CI` is explicitly falsey. We mirror that:
    // `CI=0` / `CI=false` → no vendor detection.
    if (home_rt.env_var.CI.get()) |v| {
        if (!v) return null;
    }
    return generated.detectUncachedGenerated();
}

/// Stand-in for the TypeScript-codegened `ci_info` module — the upstream
/// import is wired to a generated list of vendors. Until the Home codegen
/// runs, both functions return the no-vendor answer. The shape matches the
/// generated module so the dependency flip is a one-liner.
const generated = struct {
    fn isCIUncachedGenerated() bool {
        return false;
    }
    fn detectUncachedGenerated() ?[]const u8 {
        return null;
    }
};

const home_rt = @import("home_rt");
const std = @import("std");

test "ci_info.isCI does not crash" {
    _ = isCI();
}

test "ci_info.detectCIName returns null without codegen" {
    // The codegen-backed vendor table is parked, so detectCIName is
    // guaranteed null in the Home tree today. Make that contract explicit.
    try std.testing.expectEqual(@as(?[]const u8, null), detectCIName());
}

test "ci_info.isCI shape matches detectCIName fallback" {
    // Without the vendor table, isCI() can only reflect the CI env var.
    const ci = isCI();
    // It must be one of the two boolean values; just exercise the path.
    try std.testing.expect(ci == true or ci == false);
}
