// Copied from bun/src/runtime/cli/ci_info.zig at upstream SHA
// fd0b6f1a271fca0b8124b69f230b100f4d636af6. MIT — see ../../cli/LICENSE.bun.md.
//
// Rewrites:
//   - @import("bun")                  → @import("home")
//   - bun.env_var.CI.get()            → home_rt.env_var.CI.get()
//     (upstream returns bool-or-null and was treated as a fall-through
//     gate; Home's `env_var.CI` returns `?bool` already, so the gate
//     becomes `CI.get() orelse false`.)
//   - `bun.once(...)` memoization is parked: home_rt does not yet expose
//     the `Once` helper, so the wrappers call into the uncached body
//     each time. The detector is a handful of env_var lookups and
//     small string compares — the cost is negligible at CLI startup.
//   - `@import("ci_info")` (TypeScript-generated by
//     src/codegen/ci_info.ts) → the checked-in `ci_info_generated.zig`.
//     Keeping the generated table in-tree makes native Home builds use the
//     same provider detection even when Bun's codegen step is not running.
// No Bun→Home identifier renames apply.
//
// A modified port of ci-info@4.0.0 (https://github.com/watson/ci-info)
// Only gets the CI name, `isPR` is not implemented.
// Main implementation is generated by src/codegen/ci_info.ts.

/// returns true if the current process is running in a CI environment
pub fn isCI() bool {
    return isCIUncached();
}

/// returns the CI name, or null if the CI name could not be determined. note that this can be null even if `isCI` is true.
pub fn detectCIName() ?[]const u8 {
    return detectUncached();
}

fn isCIUncached() bool {
    if (home_rt.env_var.CI.get()) |v| return v or detectCIName() != null;
    return generated.isCIUncachedGenerated() or detectCIName() != null;
}
fn detectUncached() ?[]const u8 {
    // Upstream early-exits when `CI` is explicitly falsey. We mirror that:
    // `CI=0` / `CI=false` → no vendor detection.
    if (home_rt.env_var.CI.get()) |v| {
        if (!v) return null;
    }
    return generated.detectUncachedGenerated();
}

const generated = @import("ci_info_generated.zig");

const home_rt = @import("home");
const std = @import("std");

test "ci_info.isCI does not crash" {
    _ = isCI();
}

test "ci_info.isCI and detectCIName exercise the generated provider table" {
    _ = detectCIName();
    const ci = isCI();
    try std.testing.expect(ci == true or ci == false);
}
