[package]
name = "home-safety"
version = "0.1.0"
authors = ["Home Contributors"]
description = "Home Safety System - Unsafe blocks and safety checks"
license = "MIT"

[dependencies]
home-ast = { path = "../ast" }
home-types = { path = "../types" }

[scripts]
test = "zig test src/unsafe_blocks.zig"
