[package]
name = "comptime"
version = "0.1.0"
description = "Compile-time utilities and metaprogramming for Home"
license = "MIT"
authors = ["Home Contributors"]

[dependencies]
# No dependencies - pure compile-time code

[build]
zig_version = "0.13.0"
