[package]
name = "ion-comptime"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Compile-Time Execution - Comptime evaluation"
license = "MIT"

[dependencies]
ion-ast = { path = "../ast" }
ion-interpreter = { path = "../interpreter" }

[scripts]
test = "zig test src/comptime_executor.zig"
