use strict;
use warnings;

my $src = '/opt/homebrew/lib/node_modules/typescript/lib/_tsc.js';
open my $in, '<', $src or die "open $src: $!";

print <<'HEADER';
//! TypeScript diagnostic-code lookup table — Phase 8 §8.A.29.
//!
//! Generated at build time from upstream's `diagnosticMessages.json`
//! (extracted from the bundled `_tsc.js` since the JSON isn't shipped
//! with the npm package). Do NOT edit this file by hand; regenerate
//! via `scripts/gen-ts-diag-codes.pl` against the current TypeScript
//! install at `/opt/homebrew/lib/node_modules/typescript/lib/_tsc.js`.
//!
//! The table powers `textDocument/hover` in the LSP server — hovering
//! a `TSnnnn` token surfaces the canonical TS diagnostic definition
//! (code, category, message template, and key for cross-tool lookup).

const std = @import("std");

pub const Category = enum(u8) {
    warning = 0,
    err = 1,
    suggestion = 2,
    message = 3,
};

pub const DiagInfo = struct {
    code: u32,
    category: Category,
    key: []const u8,
    message: []const u8,
};

/// Look up a TS diagnostic code. Returns null when the code isn't
/// part of the upstream catalogue at generation time. Codes above
/// the highest observed entry resolve to null even if they're valid
/// in a newer TypeScript — bumping the install + regenerating is
/// the supported path.
pub fn lookup(code: u32) ?DiagInfo {
    return switch (code) {
HEADER

my %entries;
while (<$in>) {
    if (/diag\((\d+),\s+(\d+)\s+\/\*\s+(\w+)\s+\*\/,\s+"([^"]+)",\s+(?:"(.*)"|`(.*)`|'(.*)')\)/) {
        my ($code, $catnum, $catname, $key, $msg) = ($1, $2, $3, $4, $5 // $6 // $7);
        # Sometimes the same code is defined twice (alias forms);
        # keep the first.
        next if exists $entries{$code};
        $entries{$code} = { catname => $catname, key => $key, msg => $msg };
    }
}
close $in;

sub escape_zig {
    my ($s) = @_;
    $s =~ s/\\/\\\\/g;
    $s =~ s/"/\\"/g;
    return $s;
}

my $cat_map = { Error => 'err', Warning => 'warning', Suggestion => 'suggestion', Message => 'message' };

for my $code (sort { $a <=> $b } keys %entries) {
    my $e = $entries{$code};
    my $cat = $cat_map->{$e->{catname}} or die "unknown cat: $e->{catname}";
    my $key = escape_zig($e->{key});
    my $msg = escape_zig($e->{msg});
    print qq{        $code => .{ .code = $code, .category = .$cat, .key = "$key", .message = "$msg" },\n};
}

print <<'FOOTER';
        else => null,
    };
}

pub fn categoryLabel(c: Category) []const u8 {
    return switch (c) {
        .warning => "Warning",
        .err => "Error",
        .suggestion => "Suggestion",
        .message => "Message",
    };
}
FOOTER
