#!/usr/bin/env bash
# Manual build script for the Home compiler.
#
# Rationale: `zig build` fails on macOS 26 (Tahoe) in zig 0.15.1 / 0.16-dev
# because the build runner executable is compiled with abi=none and doesn't
# auto-link libSystem. `zig build-exe -target native-macos` DOES link libc
# correctly, so we bypass the build runner entirely and invoke the compiler
# directly with explicit module flags.
#
# `--dep` applies to the next `-M`. Root must be the first `-M` so its
# imports are the ones that follow declaration order. Sub-modules come
# after root with `--dep <name>` preceding each `-M` declaration.

set -euo pipefail
cd "$(dirname "$0")/.."

# Prefer the project's pinned zig 0.16-dev, then fall back to whatever's in
# PATH. This file expects zig 0.16+ semantics; older releases will fail
# loudly with mismatched APIs.
if [[ -z "${ZIG:-}" ]]; then
    if [[ -x "$HOME/.local/share/zig-0.16-dev/zig" ]]; then
        ZIG="$HOME/.local/share/zig-0.16-dev/zig"
    elif command -v zig >/dev/null 2>&1; then
        ZIG="$(command -v zig)"
    else
        echo "zig not found; install zig 0.16-dev or set ZIG=/path/to/zig" >&2
        exit 2
    fi
fi
OUT="zig-out/bin/home"
mkdir -p zig-out/bin

# Synthesize a build_options shim (normally generated by `zig build`).
cat > /tmp/home_build_options.zig <<'EOF'
pub const enable_craft: bool = false;
pub const debug_logging: bool = false;
pub const memory_tracking: bool = false;
pub const enable_ir_cache: bool = true;
pub const parallel_build: bool = true;
pub const extra_safety: bool = false;
pub const enable_profiling: bool = false;
pub const enable_coverage: bool = false;
pub const enable_sanitize_address: bool = false;
pub const enable_sanitize_undefined: bool = false;
pub const enable_sanitize_thread: bool = false;
EOF

ARGS=(
    build-exe
    -target native-macos
    -lc
    -OReleaseFast
    -fno-stack-check
    -femit-bin="$OUT"

    # --- root module (must be first -M) ---
    --dep lexer
    --dep ast
    --dep parser
    --dep types
    --dep interpreter
    --dep codegen
    --dep compiler
    --dep optimizer
    --dep formatter
    --dep linter
    --dep macros
    --dep diagnostics
    --dep comptime
    --dep pkg_manager
    --dep ir_cache
    --dep build_options
    -Mroot=src/main.zig

    # --- sub-modules in any order ---
    -Mlexer=packages/lexer/src/lexer.zig
    --dep lexer
    -Mast=packages/ast/src/ast.zig
    --dep ast
    -Mmacros=packages/macros/src/macro_system.zig
    --dep ast
    -Mdiagnostics=packages/diagnostics/src/diagnostics.zig
    --dep ast
    -Mtraits=packages/traits/src/traits.zig
    --dep ast
    -Mcomptime=packages/comptime/src/comptime.zig
    --dep ast
    -Minterpreter=packages/interpreter/src/interpreter.zig

    --dep lexer
    --dep ast
    --dep diagnostics
    --dep macros
    -Mparser=packages/parser/src/parser.zig

    --dep ast
    --dep diagnostics
    --dep traits
    --dep lexer
    --dep parser
    --dep comptime
    -Mtypes=packages/types/src/type_system.zig

    --dep ast
    --dep types
    --dep traits
    -Mgenerics=packages/generics/src/generic_system.zig

    --dep ast
    --dep lexer
    --dep parser
    --dep types
    --dep comptime
    --dep generics
    -Mcodegen=packages/codegen/src/codegen.zig

    --dep ast
    --dep types
    --dep diagnostics
    -Mcompiler=packages/compiler/src/borrow_check_pass.zig

    --dep ast
    -Moptimizer=packages/optimizer/src/pass_manager.zig

    -Mconfig=packages/config/src/config.zig

    --dep ast
    --dep lexer
    --dep parser
    -Mformatter=packages/formatter/src/formatter.zig

    --dep ast
    --dep lexer
    --dep parser
    --dep config
    -Mlinter=packages/linter/src/linter.zig

    -Mpkg_manager=packages/pkg/src/package_manager.zig
    -Mir_cache=packages/cache/src/ir_cache.zig
    -Mbuild_options=/tmp/home_build_options.zig
)

echo "+ $ZIG ${ARGS[*]}" >&2
exec "$ZIG" "${ARGS[@]}"
