#!/usr/bin/env bash
# Sync Bun's test/ corpus into packages/runtime/test/bun-corpus/ at the pinned
# upstream SHA. This is the substrate for the Phase 12 acceptance gate; the
# runtime must eventually pass 100% of these tests (see
# packages/runtime/README.md "Acceptance gate" section).
#
# Renaming Bun.* -> Home.* happens at test-runtime, NOT at copy time, so the
# corpus stays verbatim and re-syncs cleanly.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUN_REPO="${BUN_REPO:-${HOME}/Code/bun}"
DEST="${REPO_ROOT}/packages/runtime/test/bun-corpus"
PIN_FILE="${DEST}/UPSTREAM_SHA.txt"

if [[ ! -d "${BUN_REPO}/.git" ]]; then
  echo "error: Bun checkout not found at ${BUN_REPO}" >&2
  echo "       set BUN_REPO=/path/to/bun and re-run" >&2
  exit 2
fi

EXPECTED_SHA="$(tr -d '[:space:]' < "${PIN_FILE}")"
ACTUAL_SHA="$(git -C "${BUN_REPO}" rev-parse HEAD)"

echo "pinned SHA   : ${EXPECTED_SHA}"
echo "upstream HEAD: ${ACTUAL_SHA}"

if [[ "${EXPECTED_SHA}" != "${ACTUAL_SHA}" ]]; then
  echo "error: ${BUN_REPO} HEAD does not match pinned SHA." >&2
  echo "       checkout ${EXPECTED_SHA} in ${BUN_REPO} (or update ${PIN_FILE}) and re-run." >&2
  exit 1
fi

mkdir -p "${DEST}"

# Filter rules:
#   - whitelist fixtures/ and _util/ trees first so binary test inputs survive
#   - preserve binary fixtures such as .png and .wasm; many Bun tests load them
#   - drop caches, build output, logs, and platform binaries that are rebuilt
rsync -a --delete \
  --filter='- UPSTREAM_SHA.txt' \
  --filter='- /README.md' \
  --filter='- FILTERED_FILES.txt' \
  --filter='+ fixtures/***' \
  --filter='+ _util/***' \
  --filter='+ **/fixtures/***' \
  --filter='+ **/_util/***' \
  --filter='- node_modules/' \
  --filter='- .zig-cache/' \
  --filter='- .bun-cache/' \
  --filter='- coverage/' \
  --filter='- dist/' \
  --filter='- *.log' \
  --filter='- .DS_Store' \
  --filter='- *.exe' \
  --filter='- *.dylib' \
  --filter='- *.so' \
  "${BUN_REPO}/test/" "${DEST}/"

printf '%s\n' "${EXPECTED_SHA}" > "${DEST}/UPSTREAM_SHA.txt"

FILTERED_FILE="${DEST}/FILTERED_FILES.txt"
{
  echo "# Files intentionally not copied from Bun test/"
  echo "#"
  echo "# Generated by scripts/sync-bun-tests.sh at upstream ${EXPECTED_SHA}."
  echo "# .DS_Store and generated/cache outputs may appear here. Runtime fixtures"
  echo "# such as .png and .wasm are preserved so the corpus remains executable."
  FILTERED_ENTRIES="$(comm -23 \
    <(cd "${BUN_REPO}/test" && find . \( -type f -o -type l \) | sort) \
    <(cd "${DEST}" && find . \( -type f -o -type l \) ! -name 'FILTERED_FILES.txt' | sort))"
  if [[ -n "${FILTERED_ENTRIES}" ]]; then
    echo
    printf '%s\n' "${FILTERED_ENTRIES}"
  fi
} > "${FILTERED_FILE}"

COUNT="$(find "${DEST}" \( -type f -o -type l \) ! -name 'UPSTREAM_SHA.txt' ! -name 'FILTERED_FILES.txt' | wc -l | tr -d ' ')"
SIZE="$(du -sh "${DEST}" | awk '{print $1}')"
echo "synced ${COUNT} upstream corpus files (${SIZE}) into ${DEST}"
