#!/usr/bin/env bash
# Sync Bun's Git-tracked test/ corpus into packages/runtime/test/bun-corpus/ at
# the pinned upstream SHA. This is the substrate for the Phase 12 acceptance
# gate; the runtime must eventually pass 100% of these tests (see
# packages/runtime/README.md "Acceptance gate" section).
#
# Renaming Bun.* -> Home.* happens at test-runtime, NOT at copy time, so the
# corpus stays verbatim and re-syncs cleanly.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUN_REPO="${BUN_REPO:-${HOME}/Code/bun}"
DEST="${REPO_ROOT}/packages/runtime/test/bun-corpus"
PIN_FILE="${DEST}/UPSTREAM_SHA.txt"
TRACKED_FILE="${DEST}/BUN_TRACKED_FILES.txt"
MATERIALIZED_FILE="${DEST}/MATERIALIZED_FILES.txt"

if [[ ! -d "${BUN_REPO}/.git" ]]; then
  echo "error: Bun checkout not found at ${BUN_REPO}" >&2
  echo "       set BUN_REPO=/path/to/bun and re-run" >&2
  exit 2
fi

if [[ ! -f "${MATERIALIZED_FILE}" ]]; then
  echo "error: materialized-fixture manifest not found at ${MATERIALIZED_FILE}" >&2
  exit 2
fi

EXPECTED_SHA="$(tr -d '[:space:]' < "${PIN_FILE}")"
ACTUAL_SHA="$(git -C "${BUN_REPO}" rev-parse HEAD)"

echo "pinned SHA   : ${EXPECTED_SHA}"
echo "upstream HEAD: ${ACTUAL_SHA}"

if [[ "${EXPECTED_SHA}" != "${ACTUAL_SHA}" ]]; then
  echo "error: ${BUN_REPO} HEAD does not match pinned SHA." >&2
  echo "       checkout ${EXPECTED_SHA} in ${BUN_REPO} (or update ${PIN_FILE}) and re-run." >&2
  exit 1
fi

mkdir -p "${DEST}"

# Extract the pinned commit rather than copying the checkout. Bun tests generate
# ignored build output in test/ and installs can populate ignored node_modules/
# trees. Conversely, Bun intentionally tracks fixture node_modules/ entries.
# The Git tree is the only source that distinguishes those two cases exactly.
SOURCE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/home-bun-corpus.XXXXXX")"
trap 'rm -rf "${SOURCE_DIR}"' EXIT
git -C "${BUN_REPO}" archive --format=tar "${EXPECTED_SHA}:test" | tar -xf - -C "${SOURCE_DIR}"

# MATERIALIZED_FILES.txt names upstream-generated fixtures that Home checks in
# because the imported Node tests consume them. Preserve only those explicit
# adjuncts and the four provenance files while deleting all other stale output.
rsync -a --delete \
  --filter='protect /UPSTREAM_SHA.txt' \
  --filter='protect /BUN_TRACKED_FILES.txt' \
  --filter='protect /FILTERED_FILES.txt' \
  --filter='protect /MATERIALIZED_FILES.txt' \
  --filter='protect /js/node/test/fixtures/wpt/***' \
  "${SOURCE_DIR}/" "${DEST}/"

printf '%s\n' "${EXPECTED_SHA}" > "${DEST}/UPSTREAM_SHA.txt"
git -C "${BUN_REPO}" -c core.quotePath=false ls-tree -r --name-only "${EXPECTED_SHA}" test/ \
  | sed 's#^test/##' \
  | LC_ALL=C sort > "${TRACKED_FILE}"

FILTERED_FILE="${DEST}/FILTERED_FILES.txt"
{
  echo "# Files intentionally not copied from Bun test/"
  echo "#"
  echo "# Generated by scripts/sync-bun-tests.sh at upstream ${EXPECTED_SHA}."
  echo "# The pinned Git tree is copied without filters. Ignored/generated files in"
  echo "# the Bun working tree are deliberately outside the corpus manifest."
} > "${FILTERED_FILE}"

COUNT="$(wc -l < "${TRACKED_FILE}" | tr -d ' ')"
SIZE="$(du -sh "${DEST}" | awk '{print $1}')"
echo "synced ${COUNT} Git-tracked upstream corpus entries (${SIZE}) into ${DEST}"
