[package]
name = "home-pkg"
version = "0.1.0"
authors = ["Home Contributors"]
description = "Home Package Manager - Dependency management and installation"
license = "MIT"

[dependencies]
# Standalone package manager

[scripts]
test = "zig test src/package_manager.zig"
