[package]
name = "home-async"
version = "0.1.0"
authors = ["Home Contributors"]
description = "Home Async Runtime - Asynchronous programming and concurrency"
license = "MIT"

[dependencies]
# May need home-types for async type checking

[scripts]
test = "zig test src/async_runtime.zig"
