name: 'Setup Home'
description: 'Setup the Home programming language compiler in your GitHub Actions workflow'
author: 'Home Contributors'
branding:
  icon: 'zap'
  color: 'purple'

inputs:
  home-version:
    description: 'Version of Home to install (e.g., "latest", "0.1.0", or "canary")'
    required: false
    default: 'latest'

  home-version-file:
    description: 'Path to a file containing the Home version (e.g., ".home-version")'
    required: false

  cache:
    description: 'Enable caching of Home installation'
    required: false
    default: 'true'

  scope:
    description: 'Scope for package registry authentication'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
