[package]
name = "ion-action"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "GitHub Action for setting up Ion in CI/CD workflows"
license = "MIT"

[dependencies]
# This is a TypeScript/JavaScript package, no Ion dependencies

[scripts]
install = "bun install"
build = "bun run build"
package = "bun run package"
test = "bun test"
format = "bun run format"
