[package]
name = "ion-traits"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Trait System - Trait definitions and implementations"
license = "MIT"

[dependencies]
ion-ast = { path = "../ast" }
ion-types = { path = "../types" }

[scripts]
test = "zig test src/trait_system.zig"
