[package]
name = "linker"
version = "0.1.0"
description = "Linker script control and generation for Home OS"
authors = ["Home Team"]
license = "MIT"

[dependencies]
basics = { path = "../basics" }

[features]
validation = true
symbol_analysis = true
memory_map = true
