// Copied from bun/src/cli/list-of-yarn-commands.zig at upstream SHA
// fd0b6f1a271fca0b8124b69f230b100f4d636af6. MIT — see LICENSE.bun.md.
// Imports rewritten: @import("bun") → @import("home").

pub const all_yarn_commands = home_rt.ComptimeStringMap(void, .{
    // yarn v2.3 commands
    .{"add"},
    .{"bin"},
    .{"cache"},
    .{"config"},
    .{"dedupe"},
    .{"dlx"},
    .{"exec"},
    .{"explain"},
    .{"info"},
    .{"init"},
    .{"install"},
    .{"link"},
    .{"node"},
    .{"npm"},
    .{"pack"},
    .{"patch"},
    .{"plugin"},
    .{"rebuild"},
    .{"remove"},
    .{"run"},
    .{"set"},
    .{"unplug"},
    .{"up"},
    .{"why"},
    .{"workspace"},
    .{"workspaces"},

    // yarn v1 commands
    .{"access"},
    .{"add"},
    .{"audit"},
    .{"autoclean"},
    .{"bin"},
    .{"cache"},
    .{"check"},
    .{"config"},
    .{"create"},
    .{"exec"},
    .{"generate-lock-entry"},
    .{"generateLockEntry"},
    .{"global"},
    .{"help"},
    .{"import"},
    .{"info"},
    .{"init"},
    .{"install"},
    .{"licenses"},
    .{"link"},
    .{"list"},
    .{"login"},
    .{"logout"},
    .{"node"},
    .{"outdated"},
    .{"owner"},
    .{"pack"},
    .{"policies"},
    .{"publish"},
    .{"remove"},
    .{"run"},
    .{"tag"},
    .{"team"},
    .{"unlink"},
    .{"unplug"},
    .{"upgrade"},
    .{"upgrade-interactive"},
    .{"upgradeInteractive"},
    .{"version"},
    .{"versions"},
    .{"why"},
    .{"workspace"},
    .{"workspaces"},
});

const home_rt = @import("home");
