//! Candidate lines for source directive parsers. This preserves complete
//! lines and byte order; callers still decide whether a directive is valid.
const std = @import("std");

pub const Iterator = struct {
    source: []const u8,
    cursor: usize = 0,

    pub fn next(self: *Iterator) ?[]const u8 {
        const at = std.mem.indexOfScalarPos(u8, self.source, self.cursor, '@') orelse {
            self.cursor = self.source.len;
            return null;
        };
        const line_start = if (std.mem.lastIndexOfScalar(u8, self.source[self.cursor..at], '\n')) |newline|
            self.cursor + newline + 1
        else
            self.cursor;
        const line_end = std.mem.indexOfScalarPos(u8, self.source, at + 1, '\n') orelse self.source.len;
        self.cursor = if (line_end == self.source.len) line_end else line_end + 1;
        return self.source[line_start..line_end];
    }
};

fn expectEquivalent(source: []const u8) !void {
    var expected = std.mem.splitScalar(u8, source, '\n');
    var actual: Iterator = .{ .source = source };
    while (expected.next()) |line| {
        if (std.mem.indexOfScalar(u8, line, '@') == null) continue;
        const candidate = actual.next() orelse return error.MissingCandidateLine;
        try std.testing.expectEqualStrings(line, candidate);
        // Keep source offsets as well as contents: duplicate lines must not
        // collapse or move diagnostic anchors to a different occurrence.
        try std.testing.expectEqual(@intFromPtr(line.ptr), @intFromPtr(candidate.ptr));
    }
    try std.testing.expect(actual.next() == null);
    try std.testing.expect(actual.next() == null);
}

test "directive lines: preserve whole lines offsets duplicates and newline edges" {
    for ([_][]const u8{
        "",
        "plain source without directives",
        "\n\n\n",
        "@",
        "@\n",
        "\n\n@\n\n",
        "prefix @first @second suffix\nplain\n@next",
        "@same\n@same\n@same",
        "\r\n  /* @checkJs: true */\r\nplain\r\n@allowJs:false\r\n",
        "\"@inString\" /* @comment */\n\x00\xff@byte\xc3\xa9",
        "@first\r@second",
    }) |source| try expectEquivalent(source);
}

test "directive lines: generated bytes match filtered splitScalar" {
    var seed: u32 = 0x42a71;
    var buffer: [1024]u8 = undefined;
    for (0..1024) |round| {
        const len = round % buffer.len;
        for (buffer[0..len]) |*byte| {
            seed = seed *% 1664525 +% 1013904223;
            byte.* = @truncate(seed >> 24);
        }
        if (len > 0) buffer[seed % len] = '@';
        try expectEquivalent(buffer[0..len]);
    }
}
