[package]
name = "home-tools"
version = "0.1.0"
authors = ["Home Contributors"]
description = "Home Developer Tools - Documentation generator and utilities"
license = "MIT"

[dependencies]
home-ast = { path = "../ast" }
home-parser = { path = "../parser" }

[scripts]
test = "zig test src/doc_generator.zig"
