[package]
name = "home-interpreter"
version = "0.1.0"
authors = ["Home Contributors"]
description = "Home Interpreter - Runtime execution engine"
license = "MIT"

[dependencies]
home-ast = { path = "../ast" }

[scripts]
test = "zig test src/interpreter.zig"
