[package]
name = "ion-interpreter"
version = "0.1.0"
authors = ["Ion Contributors"]
description = "Ion Interpreter - Runtime execution engine"
license = "MIT"

[dependencies]
ion-ast = { path = "../ast" }

[scripts]
test = "zig test src/interpreter.zig"
